# TCL File Generated by Component Editor 25.1
# Wed Jun 03 21:34:17 BST 2026
# DO NOT MODIFY


# 
# odocrypt_top "odocrypt_top" v1.0
#  2026.06.03.21:34:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module odocrypt_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME odocrypt_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME odocrypt_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file odocrypt_top.v VERILOG PATH ../src/odocrypt_top.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 

