# =============================================================================
# soc_system.tcl
# Rebuilds the Platform Designer system for the QMTECH Cyclone V SoC KFB board
# (32-bit dual-rank DDR3: 4x MT41K256M16 = 2 GB total)
#
# Device: 5CSXFC6C6U23I7 (Cyclone V SX, 110K LE)
#
# Usage:
#   qsys-script --script=soc_system.tcl
# then generate with:
#   qsys-generate soc_system.qsys --synthesis=VERILOG --part=5CSXFC6C6U23I7
# then source HPS pin assignments in Quartus QSF:
#   source ../qsys/soc_system/synthesis/submodules/hps_sdram_p0_pin_assignments.tcl
#
# CRITICAL: This TCL creates the Qsys system definition. The DDR3 pin locations
# are auto-generated by Qsys and must be sourced into the Quartus .qsf AFTER
# qsys-generate completes. Hand-editing DDR3 pin assignments causes conflicts.
# =============================================================================

package require -exact qsys 25.1

create_system {soc_system}

set_project_property DEVICE_FAMILY {Cyclone V}
set_project_property DEVICE        {5CSXFC6C6U23I7}

# -----------------------------------------------------------------------------
# Clock source (50 MHz fabric clock into the lightweight bridge)
# -----------------------------------------------------------------------------
add_instance clk_0 clock_source 25.1
set_instance_parameter_value clk_0 {clockFrequency}      {50000000}
set_instance_parameter_value clk_0 {clockFrequencyKnown} {true}
set_instance_parameter_value clk_0 {resetSynchronousEdges} {NONE}

# -----------------------------------------------------------------------------
# Cyclone V HPS
# -----------------------------------------------------------------------------
add_instance hps_0 altera_hps 25.1
set_instance_parameter_value hps_0 {DEVICE_FAMILY} {Cyclone V}

# FPGA <-> HPS bridges: lightweight H2F only in this reference
set_instance_parameter_value hps_0 {S2FCLK_COLDRESET_ENABLE}    {false}
set_instance_parameter_value hps_0 {S2FCLK_PENDINGRESET_ENABLE} {false}
set_instance_parameter_value hps_0 {S2FCLK_USER0CLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {S2FCLK_USER1CLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {S2FCLK_USER2CLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {F2SCLK_PERIPHCLK_ENABLE}    {false}
set_instance_parameter_value hps_0 {F2SCLK_SDRAMCLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {LWH2F_Enabled}              {true}
set_instance_parameter_value hps_0 {H2F_Width}                  {0}
set_instance_parameter_value hps_0 {F2H_Width}                  {0}
set_instance_parameter_value hps_0 {F2SINTERRUPT_Enable}        {true}

# Peripheral pin-mux (matches the board schematic)
set_instance_parameter_value hps_0 {EMAC0_Mode}      {N/A}
set_instance_parameter_value hps_0 {EMAC1_Mode}      {RGMII}
set_instance_parameter_value hps_0 {EMAC1_PinMuxing} {HPS I/O Set 0}
set_instance_parameter_value hps_0 {USB0_Mode}       {N/A}
set_instance_parameter_value hps_0 {USB1_Mode}       {SDR}
set_instance_parameter_value hps_0 {USB1_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {SDIO_Mode}       {8-bit Data}
set_instance_parameter_value hps_0 {SDIO_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {QSPI_Mode}       {N/A}
set_instance_parameter_value hps_0 {NAND_Mode}       {N/A}
set_instance_parameter_value hps_0 {UART0_Mode}      {No Flow Control}
set_instance_parameter_value hps_0 {UART0_PinMuxing} {HPS I/O Set 0}
set_instance_parameter_value hps_0 {UART1_Mode}      {N/A}
set_instance_parameter_value hps_0 {I2C0_Mode}       {I2C}
set_instance_parameter_value hps_0 {I2C0_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {I2C1_Mode}       {I2C}
set_instance_parameter_value hps_0 {I2C1_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {SPIM0_Mode}      {Single Slave Select}
set_instance_parameter_value hps_0 {SPIM0_PinMuxing} {HPS I/O Set 0}
set_instance_parameter_value hps_0 {CAN0_Mode}       {N/A}
set_instance_parameter_value hps_0 {CAN1_Mode}       {N/A}
set_instance_parameter_value hps_0 {TRACE_Mode}      {N/A}
set_instance_parameter_value hps_0 {GPIO_Mode}       {GPIO}

# HPS SDRAM (DDR3): Single-rank, 32-bit total (2x MT41K256M16 = 1GB)
# Schematic shows: CKE[1:0], CS_n[1:0], ODT[1:0] (but only CS_n[0] used for single-rank)
set_instance_parameter_value hps_0 {MEM_DQ_WIDTH}       {32}
set_instance_parameter_value hps_0 {MEM_DQ_PER_DQS}     {8}
set_instance_parameter_value hps_0 {MEM_CK_WIDTH}       {1}
set_instance_parameter_value hps_0 {MEM_DQS_WIDTH}      {2}
set_instance_parameter_value hps_0 {MEM_DM_WIDTH}       {4}
set_instance_parameter_value hps_0 {MEM_BANKADDR_WIDTH} {3}
set_instance_parameter_value hps_0 {MEM_ROW_ADDR_WIDTH}  {14}
set_instance_parameter_value hps_0 {MEM_COL_ADDR_WIDTH}  {10}
set_instance_parameter_value hps_0 {MEM_CS_WIDTH}       {1}

# -----------------------------------------------------------------------------
# OdoCrypt miner register block (component: odocrypt_top_hw.tcl, same dir)
# -----------------------------------------------------------------------------
add_instance odo_0 odocrypt_top 1.0

# -----------------------------------------------------------------------------
# SPI display (ILI9341-class TFT). Fixed SCLK ≈ 25 MHz (50 MHz / 2).
# Linux driver: spi-altera-platform ("altr,spi-1.0") + fbtft fb_ili9341.
# -----------------------------------------------------------------------------
add_instance spi_lcd altera_avalon_spi 25.1
set_instance_parameter_value spi_lcd {clockPhase}      {0}
set_instance_parameter_value spi_lcd {clockPolarity}   {0}
set_instance_parameter_value spi_lcd {dataWidth}       {8}
set_instance_parameter_value spi_lcd {masterSPI}       {true}
set_instance_parameter_value spi_lcd {numberOfSlaves}  {1}
set_instance_parameter_value spi_lcd {targetClockRate} {25000000.0}

# -----------------------------------------------------------------------------
# SPI touch controller (XPT2046/ADS7846). Fixed SCLK ≈ 1.56 MHz (max 2.5 MHz).
# Linux driver: spi-altera-platform + ads7846 touchscreen.
# -----------------------------------------------------------------------------
add_instance spi_touch altera_avalon_spi 25.1
set_instance_parameter_value spi_touch {clockPhase}      {0}
set_instance_parameter_value spi_touch {clockPolarity}   {0}
set_instance_parameter_value spi_touch {dataWidth}       {8}
set_instance_parameter_value spi_touch {masterSPI}       {true}
set_instance_parameter_value spi_touch {numberOfSlaves}  {1}
set_instance_parameter_value spi_touch {targetClockRate} {2000000.0}

# -----------------------------------------------------------------------------
# PIO: LCD control lines (bit0 = D/C, bit1 = RESET_n, bit2 = backlight)
# -----------------------------------------------------------------------------
add_instance pio_lcd altera_avalon_pio 25.1
set_instance_parameter_value pio_lcd {direction} {Output}
set_instance_parameter_value pio_lcd {width}     {3}
set_instance_parameter_value pio_lcd {resetValue} {0x2}

# -----------------------------------------------------------------------------
# PIO: inputs with IRQ (bit0 = touch PENIRQ_n, bit1 = KEY0, bit2 = KEY1)
# -----------------------------------------------------------------------------
add_instance pio_in altera_avalon_pio 25.1
set_instance_parameter_value pio_in {direction}      {Input}
set_instance_parameter_value pio_in {width}          {3}
set_instance_parameter_value pio_in {edgeType}       {FALLING}
set_instance_parameter_value pio_in {captureEdge}    {true}
set_instance_parameter_value pio_in {generateIRQ}    {true}
set_instance_parameter_value pio_in {irqType}        {EDGE}

# -----------------------------------------------------------------------------
# PIO: board LEDs (8 bits, status display)
# -----------------------------------------------------------------------------
add_instance pio_led altera_avalon_pio 25.1
set_instance_parameter_value pio_led {direction} {Output}
set_instance_parameter_value pio_led {width}     {8}
set_instance_parameter_value pio_led {resetValue} {0x0}

# -----------------------------------------------------------------------------
# Clocks and resets to all fabric peripherals
# -----------------------------------------------------------------------------
foreach inst {odo_0 spi_lcd spi_touch pio_lcd pio_in pio_led} {
    add_connection clk_0.clk       ${inst}.clk
    add_connection clk_0.clk_reset ${inst}.reset
}
add_connection clk_0.clk       hps_0.h2f_lw_axi_clock
add_connection clk_0.clk_reset hps_0.h2f_lw_axi_reset

# -----------------------------------------------------------------------------
# LWH2F bridge → peripheral address map (byte offsets from 0xFF200000).
# odo_0 MUST stay at 0x0000: hps/hps_regs.h assumes MINER_BASE_OFFSET = 0.
# -----------------------------------------------------------------------------
add_connection hps_0.h2f_lw_axi_master odo_0.s0
set_connection_parameter_value hps_0.h2f_lw_axi_master/odo_0.s0 baseAddress {0x0000}

add_connection hps_0.h2f_lw_axi_master spi_lcd.spi_control_port
set_connection_parameter_value hps_0.h2f_lw_axi_master/spi_lcd.spi_control_port baseAddress {0x1000}

add_connection hps_0.h2f_lw_axi_master spi_touch.spi_control_port
set_connection_parameter_value hps_0.h2f_lw_axi_master/spi_touch.spi_control_port baseAddress {0x1100}

add_connection hps_0.h2f_lw_axi_master pio_lcd.s1
set_connection_parameter_value hps_0.h2f_lw_axi_master/pio_lcd.s1 baseAddress {0x1200}

add_connection hps_0.h2f_lw_axi_master pio_in.s1
set_connection_parameter_value hps_0.h2f_lw_axi_master/pio_in.s1 baseAddress {0x1300}

add_connection hps_0.h2f_lw_axi_master pio_led.s1
set_connection_parameter_value hps_0.h2f_lw_axi_master/pio_led.s1 baseAddress {0x1400}

# -----------------------------------------------------------------------------
# Interrupts → HPS f2h_irq0 (GIC: 72 + n on Cyclone V)
#   n=0: spi_lcd, n=1: spi_touch, n=2: pio_in (touch pen / keys)
# -----------------------------------------------------------------------------
add_connection hps_0.f2h_irq0 spi_lcd.irq
set_connection_parameter_value hps_0.f2h_irq0/spi_lcd.irq irqNumber {0}
add_connection hps_0.f2h_irq0 spi_touch.irq
set_connection_parameter_value hps_0.f2h_irq0/spi_touch.irq irqNumber {1}
add_connection hps_0.f2h_irq0 pio_in.irq
set_connection_parameter_value hps_0.f2h_irq0/pio_in.irq irqNumber {2}

# -----------------------------------------------------------------------------
# Export interfaces
# -----------------------------------------------------------------------------
# Clock and reset (user provides 50 MHz clock)
add_interface          clk clock sink
set_interface_property clk EXPORT_OF clk_0.clk_in
add_interface          reset reset sink
set_interface_property reset EXPORT_OF clk_0.clk_in_reset

# Memory (DDR3)
add_interface          memory conduit end
set_interface_property memory EXPORT_OF hps_0.memory

# HPS I/O (peripherals: Ethernet, USB, SD, UART, I2C, SPI, GPIO)
add_interface          hps_io conduit end
set_interface_property hps_io EXPORT_OF hps_0.hps_io

# SPI display / touch external pins
add_interface          spi_lcd conduit end
set_interface_property spi_lcd EXPORT_OF spi_lcd.external
add_interface          spi_touch conduit end
set_interface_property spi_touch EXPORT_OF spi_touch.external

# PIO external pins
add_interface          pio_lcd conduit end
set_interface_property pio_lcd EXPORT_OF pio_lcd.external_connection
add_interface          pio_in conduit end
set_interface_property pio_in EXPORT_OF pio_in.external_connection
add_interface          pio_led conduit end
set_interface_property pio_led EXPORT_OF pio_led.external_connection

# Save system
save_system {soc_system.qsys}
