# =============================================================================
# soc_system.tcl
# Rebuilds the Platform Designer system for the QMTECH Cyclone V SoC KFB board
# (32-bit dual-rank DDR3: 4x MT41K256M16 = 2 GB total)
#
# Device: 5CSXFC6C6U23I7 (Cyclone V SX, 110K LE)
#
# Usage:
#   qsys-script --script=soc_system.tcl
# then generate with:
#   qsys-generate soc_system.qsys --synthesis=VERILOG --part=5CSXFC6C6U23I7
# then source HPS pin assignments in Quartus QSF:
#   source ../qsys/soc_system/synthesis/submodules/hps_sdram_p0_pin_assignments.tcl
#
# CRITICAL: This TCL creates the Qsys system definition. The DDR3 pin locations
# are auto-generated by Qsys and must be sourced into the Quartus .qsf AFTER
# qsys-generate completes. Hand-editing DDR3 pin assignments causes conflicts.
# =============================================================================

package require -exact qsys 25.1

create_system {soc_system}

set_project_property DEVICE_FAMILY {Cyclone V}
set_project_property DEVICE        {5CSXFC6C6U23I7}

# -----------------------------------------------------------------------------
# Clock source (50 MHz fabric clock into the lightweight bridge)
# -----------------------------------------------------------------------------
add_instance clk_0 clock_source 25.1
set_instance_parameter_value clk_0 {clockFrequency}      {50000000}
set_instance_parameter_value clk_0 {clockFrequencyKnown} {true}
set_instance_parameter_value clk_0 {resetSynchronousEdges} {NONE}

# -----------------------------------------------------------------------------
# Cyclone V HPS
# -----------------------------------------------------------------------------
add_instance hps_0 altera_hps 25.1
set_instance_parameter_value hps_0 {DEVICE_FAMILY} {Cyclone V}

# FPGA <-> HPS bridges: lightweight H2F only in this reference
set_instance_parameter_value hps_0 {S2FCLK_COLDRESET_ENABLE}    {false}
set_instance_parameter_value hps_0 {S2FCLK_PENDINGRESET_ENABLE} {false}
set_instance_parameter_value hps_0 {S2FCLK_USER0CLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {S2FCLK_USER1CLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {S2FCLK_USER2CLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {F2SCLK_PERIPHCLK_ENABLE}    {false}
set_instance_parameter_value hps_0 {F2SCLK_SDRAMCLK_ENABLE}     {false}
set_instance_parameter_value hps_0 {LWH2F_Enabled}              {true}
set_instance_parameter_value hps_0 {H2F_Width}                  {0}
set_instance_parameter_value hps_0 {F2H_Width}                  {0}
set_instance_parameter_value hps_0 {F2SInterruptsEnable}        {true}

# Peripheral pin-mux (matches the board schematic)
set_instance_parameter_value hps_0 {EMAC0_Mode}      {N/A}
set_instance_parameter_value hps_0 {EMAC1_Mode}      {RGMII}
set_instance_parameter_value hps_0 {EMAC1_PinMuxing} {HPS I/O Set 0}
set_instance_parameter_value hps_0 {USB0_Mode}       {N/A}
set_instance_parameter_value hps_0 {USB1_Mode}       {SDR}
set_instance_parameter_value hps_0 {USB1_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {SDIO_Mode}       {8-bit Data}
set_instance_parameter_value hps_0 {SDIO_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {QSPI_Mode}       {N/A}
set_instance_parameter_value hps_0 {NAND_Mode}       {N/A}
set_instance_parameter_value hps_0 {UART0_Mode}      {No Flow Control}
set_instance_parameter_value hps_0 {UART0_PinMuxing} {HPS I/O Set 0}
set_instance_parameter_value hps_0 {UART1_Mode}      {N/A}
set_instance_parameter_value hps_0 {I2C0_Mode}       {I2C}
set_instance_parameter_value hps_0 {I2C0_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {I2C1_Mode}       {I2C}
set_instance_parameter_value hps_0 {I2C1_PinMuxing}  {HPS I/O Set 0}
set_instance_parameter_value hps_0 {SPIM0_Mode}      {Single Slave Select}
set_instance_parameter_value hps_0 {SPIM0_PinMuxing} {HPS I/O Set 0}
set_instance_parameter_value hps_0 {CAN0_Mode}       {N/A}
set_instance_parameter_value hps_0 {CAN1_Mode}       {N/A}
set_instance_parameter_value hps_0 {TRACE_Mode}      {N/A}
set_instance_parameter_value hps_0 {GPIO_Mode}       {GPIO}

# HPS SDRAM (DDR3): Single-rank, 32-bit total (2x MT41K256M16 = 1GB)
# Schematic shows: CKE[1:0], CS_n[1:0], ODT[1:0] (but only CS_n[0] used for single-rank)
set_instance_parameter_value hps_0 {MEM_DQ_WIDTH}       {32}
set_instance_parameter_value hps_0 {MEM_DQ_PER_DQS}     {8}
set_instance_parameter_value hps_0 {MEM_CK_WIDTH}       {1}
set_instance_parameter_value hps_0 {MEM_DQS_WIDTH}      {2}
set_instance_parameter_value hps_0 {MEM_DM_WIDTH}       {4}
set_instance_parameter_value hps_0 {MEM_BANKADDR_WIDTH} {3}
set_instance_parameter_value hps_0 {MEM_ROW_ADDR_WIDTH}  {14}
set_instance_parameter_value hps_0 {MEM_COL_ADDR_WIDTH}  {10}
set_instance_parameter_value hps_0 {MEM_CS_WIDTH}       {1}

# Export interfaces
# Clock and reset (user provides 50 MHz clock)
add_interface          clk clock sink
set_interface_property clk EXPORT_OF clk_0.clk_in
add_interface          reset reset sink
set_interface_property reset EXPORT_OF clk_0.clk_in_reset

# Memory (DDR3)
add_interface          memory conduit end
set_interface_property memory EXPORT_OF hps_0.memory

# HPS I/O (peripherals: Ethernet, USB, SD, UART, I2C, SPI, GPIO)
add_interface          hps_io conduit end
set_interface_property hps_io EXPORT_OF hps_0.hps_io

# MPU interrupt events (export for future use)
add_interface          h2f_mpu_events conduit end
set_interface_property h2f_mpu_events EXPORT_OF hps_0.h2f_mpu_events

# Lightweight bridge master (export for future odocrypt_top integration)
add_interface          h2f_lw_axi_master avalon_master end
set_interface_property h2f_lw_axi_master EXPORT_OF hps_0.h2f_lw_axi_master

# Save system
save_system {soc_system.qsys}
