/*
 * odo_ui.c — touch status panel for the odo-miner Cyclone V SoC.
 *
 * Renders a mining dashboard on the ILI9341 framebuffer (/dev/fb0, RGB565,
 * 320x240 with rotate=270 in the DTS) and handles the XPT2046 resistive
 * touch (/dev/input/event*, ads7846 driver) for two actions:
 *
 *     [RESTART MINER]  — restarts the odod/odo-miner service
 *     [REBOOT]         — reboots the board (with confirmation)
 *
 * Status comes from the JSON snapshot odo-miner writes on every heartbeat
 * (/run/odod/status.json). Parsing is deliberately primitive (strstr) — the
 * file is machine-generated by miner.c with known keys.
 *
 * Build: make            (in sw/odo-ui; cross-compile with CC=...-gcc)
 * Run:   odo-ui [status.json path]
 */

#define _POSIX_C_SOURCE 200809L
#define _DEFAULT_SOURCE     /* sync() */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <signal.h>
#include <dirent.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <linux/fb.h>
#include <linux/input.h>

/* ------------------------------------------------------------------ */
/* 8x8 bitmap font, ASCII 32..127 (public domain, classic IBM style)  */
/* Each glyph: 8 bytes, LSB = leftmost pixel.                          */
/* ------------------------------------------------------------------ */
static const uint8_t font8x8[96][8] = {
 {0,0,0,0,0,0,0,0},{0x18,0x3C,0x3C,0x18,0x18,0,0x18,0},
 {0x36,0x36,0,0,0,0,0,0},{0x36,0x36,0x7F,0x36,0x7F,0x36,0x36,0},
 {0x0C,0x3E,0x03,0x1E,0x30,0x1F,0x0C,0},{0,0x63,0x33,0x18,0x0C,0x66,0x63,0},
 {0x1C,0x36,0x1C,0x6E,0x3B,0x33,0x6E,0},{0x06,0x06,0x03,0,0,0,0,0},
 {0x18,0x0C,0x06,0x06,0x06,0x0C,0x18,0},{0x06,0x0C,0x18,0x18,0x18,0x0C,0x06,0},
 {0,0x66,0x3C,0xFF,0x3C,0x66,0,0},{0,0x0C,0x0C,0x3F,0x0C,0x0C,0,0},
 {0,0,0,0,0,0x0C,0x0C,0x06},{0,0,0,0x3F,0,0,0,0},
 {0,0,0,0,0,0x0C,0x0C,0},{0x60,0x30,0x18,0x0C,0x06,0x03,0x01,0},
 {0x3E,0x63,0x73,0x7B,0x6F,0x67,0x3E,0},{0x0C,0x0E,0x0C,0x0C,0x0C,0x0C,0x3F,0},
 {0x1E,0x33,0x30,0x1C,0x06,0x33,0x3F,0},{0x1E,0x33,0x30,0x1C,0x30,0x33,0x1E,0},
 {0x38,0x3C,0x36,0x33,0x7F,0x30,0x78,0},{0x3F,0x03,0x1F,0x30,0x30,0x33,0x1E,0},
 {0x1C,0x06,0x03,0x1F,0x33,0x33,0x1E,0},{0x3F,0x33,0x30,0x18,0x0C,0x0C,0x0C,0},
 {0x1E,0x33,0x33,0x1E,0x33,0x33,0x1E,0},{0x1E,0x33,0x33,0x3E,0x30,0x18,0x0E,0},
 {0,0x0C,0x0C,0,0,0x0C,0x0C,0},{0,0x0C,0x0C,0,0,0x0C,0x0C,0x06},
 {0x18,0x0C,0x06,0x03,0x06,0x0C,0x18,0},{0,0,0x3F,0,0,0x3F,0,0},
 {0x06,0x0C,0x18,0x30,0x18,0x0C,0x06,0},{0x1E,0x33,0x30,0x18,0x0C,0,0x0C,0},
 {0x3E,0x63,0x7B,0x7B,0x7B,0x03,0x1E,0},{0x0C,0x1E,0x33,0x33,0x3F,0x33,0x33,0},
 {0x3F,0x66,0x66,0x3E,0x66,0x66,0x3F,0},{0x3C,0x66,0x03,0x03,0x03,0x66,0x3C,0},
 {0x1F,0x36,0x66,0x66,0x66,0x36,0x1F,0},{0x7F,0x46,0x16,0x1E,0x16,0x46,0x7F,0},
 {0x7F,0x46,0x16,0x1E,0x16,0x06,0x0F,0},{0x3C,0x66,0x03,0x03,0x73,0x66,0x7C,0},
 {0x33,0x33,0x33,0x3F,0x33,0x33,0x33,0},{0x1E,0x0C,0x0C,0x0C,0x0C,0x0C,0x1E,0},
 {0x78,0x30,0x30,0x30,0x33,0x33,0x1E,0},{0x67,0x66,0x36,0x1E,0x36,0x66,0x67,0},
 {0x0F,0x06,0x06,0x06,0x46,0x66,0x7F,0},{0x63,0x77,0x7F,0x7F,0x6B,0x63,0x63,0},
 {0x63,0x67,0x6F,0x7B,0x73,0x63,0x63,0},{0x1C,0x36,0x63,0x63,0x63,0x36,0x1C,0},
 {0x3F,0x66,0x66,0x3E,0x06,0x06,0x0F,0},{0x1E,0x33,0x33,0x33,0x3B,0x1E,0x38,0},
 {0x3F,0x66,0x66,0x3E,0x36,0x66,0x67,0},{0x1E,0x33,0x07,0x0E,0x38,0x33,0x1E,0},
 {0x3F,0x2D,0x0C,0x0C,0x0C,0x0C,0x1E,0},{0x33,0x33,0x33,0x33,0x33,0x33,0x3F,0},
 {0x33,0x33,0x33,0x33,0x33,0x1E,0x0C,0},{0x63,0x63,0x63,0x6B,0x7F,0x77,0x63,0},
 {0x63,0x63,0x36,0x1C,0x1C,0x36,0x63,0},{0x33,0x33,0x33,0x1E,0x0C,0x0C,0x1E,0},
 {0x7F,0x63,0x31,0x18,0x4C,0x66,0x7F,0},{0x1E,0x06,0x06,0x06,0x06,0x06,0x1E,0},
 {0x03,0x06,0x0C,0x18,0x30,0x60,0x40,0},{0x1E,0x18,0x18,0x18,0x18,0x18,0x1E,0},
 {0x08,0x1C,0x36,0x63,0,0,0,0},{0,0,0,0,0,0,0,0xFF},
 {0x0C,0x0C,0x18,0,0,0,0,0},{0,0,0x1E,0x30,0x3E,0x33,0x6E,0},
 {0x07,0x06,0x06,0x3E,0x66,0x66,0x3B,0},{0,0,0x1E,0x33,0x03,0x33,0x1E,0},
 {0x38,0x30,0x30,0x3E,0x33,0x33,0x6E,0},{0,0,0x1E,0x33,0x3F,0x03,0x1E,0},
 {0x1C,0x36,0x06,0x0F,0x06,0x06,0x0F,0},{0,0,0x6E,0x33,0x33,0x3E,0x30,0x1F},
 {0x07,0x06,0x36,0x6E,0x66,0x66,0x67,0},{0x0C,0,0x0E,0x0C,0x0C,0x0C,0x1E,0},
 {0x30,0,0x30,0x30,0x30,0x33,0x33,0x1E},{0x07,0x06,0x66,0x36,0x1E,0x36,0x67,0},
 {0x0E,0x0C,0x0C,0x0C,0x0C,0x0C,0x1E,0},{0,0,0x33,0x7F,0x7F,0x6B,0x63,0},
 {0,0,0x1F,0x33,0x33,0x33,0x33,0},{0,0,0x1E,0x33,0x33,0x33,0x1E,0},
 {0,0,0x3B,0x66,0x66,0x3E,0x06,0x0F},{0,0,0x6E,0x33,0x33,0x3E,0x30,0x78},
 {0,0,0x3B,0x6E,0x66,0x06,0x0F,0},{0,0,0x3E,0x03,0x1E,0x30,0x1F,0},
 {0x08,0x0C,0x3E,0x0C,0x0C,0x2C,0x18,0},{0,0,0x33,0x33,0x33,0x33,0x6E,0},
 {0,0,0x33,0x33,0x33,0x1E,0x0C,0},{0,0,0x63,0x6B,0x7F,0x7F,0x36,0},
 {0,0,0x63,0x36,0x1C,0x36,0x63,0},{0,0,0x33,0x33,0x33,0x3E,0x30,0x1F},
 {0,0,0x3F,0x19,0x0C,0x26,0x3F,0},{0x38,0x0C,0x0C,0x07,0x0C,0x0C,0x38,0},
 {0x18,0x18,0x18,0,0x18,0x18,0x18,0},{0x07,0x0C,0x0C,0x38,0x0C,0x0C,0x07,0},
 {0x6E,0x3B,0,0,0,0,0,0},{0,0,0,0,0,0,0,0},
};

/* ------------------------------------------------------------------ */
/* Framebuffer                                                         */
/* ------------------------------------------------------------------ */
typedef struct {
    int fd;
    uint16_t *pix;
    int w, h, stride;   /* stride in pixels */
} fb_t;

#define RGB565(r,g,b) (uint16_t)((((r)>>3)<<11) | (((g)>>2)<<5) | ((b)>>3))

#define C_BG     RGB565(10, 12, 24)
#define C_PANEL  RGB565(24, 30, 52)
#define C_TEXT   RGB565(220, 226, 240)
#define C_DIM    RGB565(120, 128, 150)
#define C_OK     RGB565(70, 200, 120)
#define C_WARN   RGB565(240, 180, 60)
#define C_BAD    RGB565(230, 80, 80)
#define C_ACCENT RGB565(80, 160, 255)
#define C_BTN    RGB565(40, 52, 88)
#define C_BTNHI  RGB565(70, 90, 140)

static int fb_open(fb_t *fb)
{
    fb->fd = open("/dev/fb0", O_RDWR);
    if (fb->fd < 0) { perror("open /dev/fb0"); return -1; }

    struct fb_var_screeninfo v;
    struct fb_fix_screeninfo f;
    if (ioctl(fb->fd, FBIOGET_VSCREENINFO, &v) || ioctl(fb->fd, FBIOGET_FSCREENINFO, &f)) {
        perror("fb ioctl");
        return -1;
    }
    if (v.bits_per_pixel != 16) {
        fprintf(stderr, "expected 16bpp framebuffer, got %d\n", v.bits_per_pixel);
        return -1;
    }
    fb->w = (int)v.xres;
    fb->h = (int)v.yres;
    fb->stride = (int)(f.line_length / 2);
    fb->pix = mmap(NULL, (size_t)f.line_length * v.yres,
                   PROT_READ | PROT_WRITE, MAP_SHARED, fb->fd, 0);
    if (fb->pix == MAP_FAILED) { perror("mmap fb"); return -1; }
    return 0;
}

static void fb_rect(fb_t *fb, int x, int y, int w, int h, uint16_t c)
{
    if (x < 0) { w += x; x = 0; }
    if (y < 0) { h += y; y = 0; }
    if (x + w > fb->w) w = fb->w - x;
    if (y + h > fb->h) h = fb->h - y;
    for (int j = 0; j < h; j++) {
        uint16_t *row = fb->pix + (size_t)(y + j) * fb->stride + x;
        for (int i = 0; i < w; i++)
            row[i] = c;
    }
}

/* Draw text with integer scale; returns advance width */
static int fb_text(fb_t *fb, int x, int y, const char *s, int scale, uint16_t c)
{
    int x0 = x;
    for (; *s; s++) {
        unsigned ch = (unsigned char)*s;
        if (ch < 32 || ch > 127) ch = '?';
        const uint8_t *g = font8x8[ch - 32];
        for (int gy = 0; gy < 8; gy++)
            for (int gx = 0; gx < 8; gx++)
                if (g[gy] & (1 << gx))
                    fb_rect(fb, x + gx * scale, y + gy * scale, scale, scale, c);
        x += 8 * scale;
    }
    return x - x0;
}

/* ------------------------------------------------------------------ */
/* Touch input (ads7846)                                               */
/* ------------------------------------------------------------------ */
typedef struct {
    int fd;
    int raw_x, raw_y, down;
    int min_x, max_x, min_y, max_y;  /* raw calibration */
    int swap_xy, inv_x, inv_y;
} touch_t;

static int touch_open(touch_t *t)
{
    memset(t, 0, sizeof(*t));
    t->fd = -1;
    t->min_x = 150; t->max_x = 3900;
    t->min_y = 150; t->max_y = 3900;
    t->inv_y = 1;

    DIR *d = opendir("/dev/input");
    if (!d) return -1;
    struct dirent *e;
    char path[300], name[128];
    while ((e = readdir(d))) {
        if (strncmp(e->d_name, "event", 5) != 0) continue;
        snprintf(path, sizeof(path), "/dev/input/%s", e->d_name);
        int fd = open(path, O_RDONLY | O_NONBLOCK);
        if (fd < 0) continue;
        name[0] = 0;
        ioctl(fd, EVIOCGNAME(sizeof(name)), name);
        if (strstr(name, "ADS7846") || strstr(name, "ads7846")) {
            t->fd = fd;
            break;
        }
        close(fd);
    }
    closedir(d);
    return t->fd >= 0 ? 0 : -1;
}

/* Pump events; returns 1 on a fresh "tap" (release), with screen coords */
static int touch_poll(touch_t *t, fb_t *fb, int *sx, int *sy)
{
    if (t->fd < 0) return 0;
    struct input_event ev;
    int tapped = 0;
    static int was_down = 0;
    static int last_x = 0, last_y = 0;

    while (read(t->fd, &ev, sizeof(ev)) == (ssize_t)sizeof(ev)) {
        if (ev.type == EV_ABS) {
            if (ev.code == ABS_X) t->raw_x = ev.value;
            if (ev.code == ABS_Y) t->raw_y = ev.value;
        } else if (ev.type == EV_KEY && ev.code == BTN_TOUCH) {
            t->down = ev.value;
        } else if (ev.type == EV_SYN) {
            if (t->down) {
                int rx = t->raw_x, ry = t->raw_y;
                if (t->swap_xy) { int tmp = rx; rx = ry; ry = tmp; }
                long px = (long)(rx - t->min_x) * fb->w / (t->max_x - t->min_x);
                long py = (long)(ry - t->min_y) * fb->h / (t->max_y - t->min_y);
                if (t->inv_x) px = fb->w - 1 - px;
                if (t->inv_y) py = fb->h - 1 - py;
                if (px < 0) px = 0;
                if (px >= fb->w) px = fb->w - 1;
                if (py < 0) py = 0;
                if (py >= fb->h) py = fb->h - 1;
                last_x = (int)px;
                last_y = (int)py;
                was_down = 1;
            } else if (was_down) {
                was_down = 0;
                *sx = last_x;
                *sy = last_y;
                tapped = 1;
            }
        }
    }
    return tapped;
}

/* ------------------------------------------------------------------ */
/* Status file                                                         */
/* ------------------------------------------------------------------ */
typedef struct {
    char   pool[160];
    char   job_id[64];
    int    connected;
    long   epoch;
    long   epoch_next;       /* unix time of the next Odo shapechange */
    double hashrate;
    long long shares_found, shares_submitted;
    long   last_share, uptime, updated;
} status_t;

static long json_long(const char *buf, const char *key, long def)
{
    char pat[64];
    snprintf(pat, sizeof(pat), "\"%s\":", key);
    const char *p = strstr(buf, pat);
    return p ? strtol(p + strlen(pat), NULL, 10) : def;
}

static double json_double(const char *buf, const char *key, double def)
{
    char pat[64];
    snprintf(pat, sizeof(pat), "\"%s\":", key);
    const char *p = strstr(buf, pat);
    return p ? strtod(p + strlen(pat), NULL) : def;
}

static void json_string(const char *buf, const char *key, char *out, size_t out_sz)
{
    char pat[64];
    snprintf(pat, sizeof(pat), "\"%s\": \"", key);
    const char *p = strstr(buf, pat);
    out[0] = 0;
    if (!p) return;
    p += strlen(pat);
    size_t i = 0;
    while (*p && *p != '"' && i + 1 < out_sz)
        out[i++] = *p++;
    out[i] = 0;
}

static int status_read(const char *path, status_t *s)
{
    char buf[2048];
    FILE *f = fopen(path, "r");
    if (!f) return -1;
    size_t n = fread(buf, 1, sizeof(buf) - 1, f);
    fclose(f);
    buf[n] = 0;

    json_string(buf, "pool", s->pool, sizeof(s->pool));
    json_string(buf, "job_id", s->job_id, sizeof(s->job_id));
    s->connected        = strstr(buf, "\"connected\": true") != NULL;
    s->epoch            = json_long(buf, "epoch", 0);
    s->epoch_next       = json_long(buf, "epoch_next", 0);
    s->hashrate         = json_double(buf, "hashrate", 0);
    s->shares_found     = json_long(buf, "shares_found", 0);
    s->shares_submitted = json_long(buf, "shares_submitted", 0);
    s->last_share       = json_long(buf, "last_share", 0);
    s->uptime           = json_long(buf, "uptime", 0);
    s->updated          = json_long(buf, "updated", 0);
    return 0;
}

/* ------------------------------------------------------------------ */
/* UI                                                                  */
/* ------------------------------------------------------------------ */
typedef struct { int x, y, w, h; } rect_t;

static int hit(const rect_t *r, int x, int y)
{
    return x >= r->x && x < r->x + r->w && y >= r->y && y < r->y + r->h;
}

static void fmt_rate(double hps, char *out, size_t sz)
{
    if (hps >= 1e6)      snprintf(out, sz, "%.2f MH/s", hps / 1e6);
    else if (hps >= 1e3) snprintf(out, sz, "%.1f kH/s", hps / 1e3);
    else                 snprintf(out, sz, "%.0f H/s", hps);
}

static void fmt_age(long secs, char *out, size_t sz)
{
    if (secs < 0)            snprintf(out, sz, "never");
    else if (secs < 60)      snprintf(out, sz, "%lds ago", secs);
    else if (secs < 3600)    snprintf(out, sz, "%ldm ago", secs / 60);
    else                     snprintf(out, sz, "%ldh ago", secs / 3600);
}

static volatile sig_atomic_t g_stop = 0;
static void on_sig(int s) { (void)s; g_stop = 1; }

int main(int argc, char **argv)
{
    const char *status_path = argc > 1 ? argv[1] : "/run/odod/status.json";

    signal(SIGINT, on_sig);
    signal(SIGTERM, on_sig);

    fb_t fb;
    if (fb_open(&fb) != 0)
        return 1;

    touch_t tp;
    int have_touch = touch_open(&tp) == 0;
    if (!have_touch)
        fprintf(stderr, "odo-ui: no ADS7846 touch device found; display-only mode\n");

    rect_t btn_restart = { 8,            fb.h - 42, fb.w / 2 - 14, 34 };
    rect_t btn_reboot  = { fb.w / 2 + 6, fb.h - 42, fb.w / 2 - 14, 34 };

    int confirm = 0;            /* 0 none, 1 restart, 2 reboot */
    time_t confirm_at = 0;

    while (!g_stop) {
        status_t st;
        memset(&st, 0, sizeof(st));
        int have = status_read(status_path, &st) == 0;
        time_t now = time(NULL);
        int stale = !have || (st.updated && now - st.updated > 120);

        /* ---- background + header ---- */
        fb_rect(&fb, 0, 0, fb.w, fb.h, C_BG);
        fb_rect(&fb, 0, 0, fb.w, 22, C_PANEL);
        fb_text(&fb, 6, 4, "ODO-MINER", 2, C_ACCENT);
        if (stale)
            fb_text(&fb, fb.w - 8*6*2 - 6, 4, "STALE", 2, C_BAD);
        else if (st.connected)
            fb_text(&fb, fb.w - 8*4*2 - 6, 4, "POOL", 2, C_OK);
        else
            fb_text(&fb, fb.w - 8*7*2 - 6, 4, "OFFLINE", 2, C_WARN);

        /* ---- hashrate, big ---- */
        char line[128];
        fmt_rate(st.hashrate, line, sizeof(line));
        fb_text(&fb, 8, 34, line, 3, C_TEXT);

        /* ---- detail lines ---- */
        int y = 70;
        snprintf(line, sizeof(line), "POOL   %s", have ? st.pool : "?");
        fb_text(&fb, 8, y, line, 1, C_DIM); y += 14;
        snprintf(line, sizeof(line), "JOB    %s", st.job_id[0] ? st.job_id : "-");
        fb_text(&fb, 8, y, line, 1, C_DIM); y += 14;
        if (st.epoch && st.epoch_next && now >= st.epoch_next) {
            /* Boundary passed; the watcher swaps tables as soon as the pool
             * issues a job with the new-epoch ntime (seconds, typically). */
            snprintf(line, sizeof(line), "EPOCH  %ld  ROLLING NOW...", st.epoch);
            fb_text(&fb, 8, y, line, 1, C_WARN);
        } else if (st.epoch && st.epoch_next > now) {
            long left = st.epoch_next - now;
            snprintf(line, sizeof(line), "EPOCH  %ld (rolls %ldd %ldh)",
                     st.epoch, left / 86400, (left % 86400) / 3600);
            fb_text(&fb, 8, y, line, 1, C_DIM);
        } else {
            snprintf(line, sizeof(line), "EPOCH  %ld", st.epoch);
            fb_text(&fb, 8, y, line, 1, C_DIM);
        }
        y += 14;
        snprintf(line, sizeof(line), "SHARES %lld found / %lld sent",
                 st.shares_found, st.shares_submitted);
        fb_text(&fb, 8, y, line, 1, C_TEXT); y += 14;
        char age[32];
        fmt_age(st.last_share ? now - st.last_share : -1, age, sizeof(age));
        snprintf(line, sizeof(line), "LAST   %s", age);
        fb_text(&fb, 8, y, line, 1, C_TEXT); y += 14;
        snprintf(line, sizeof(line), "UPTIME %ldh %ldm",
                 st.uptime / 3600, (st.uptime % 3600) / 60);
        fb_text(&fb, 8, y, line, 1, C_DIM); y += 14;

        /* ---- buttons / confirmation ---- */
        if (confirm && now - confirm_at > 6)
            confirm = 0;     /* confirmation times out */

        if (!confirm) {
            fb_rect(&fb, btn_restart.x, btn_restart.y, btn_restart.w, btn_restart.h, C_BTN);
            fb_text(&fb, btn_restart.x + 10, btn_restart.y + 10, "RESTART MINER", 1, C_TEXT);
            fb_rect(&fb, btn_reboot.x, btn_reboot.y, btn_reboot.w, btn_reboot.h, C_BTN);
            fb_text(&fb, btn_reboot.x + 10, btn_reboot.y + 10, "REBOOT", 1, C_TEXT);
        } else {
            fb_rect(&fb, btn_restart.x, btn_restart.y, btn_restart.w, btn_restart.h, C_BAD);
            fb_text(&fb, btn_restart.x + 10, btn_restart.y + 10,
                    confirm == 1 ? "CONFIRM RESTART" : "CONFIRM REBOOT", 1, C_TEXT);
            fb_rect(&fb, btn_reboot.x, btn_reboot.y, btn_reboot.w, btn_reboot.h, C_BTNHI);
            fb_text(&fb, btn_reboot.x + 10, btn_reboot.y + 10, "CANCEL", 1, C_TEXT);
        }

        /* ---- input ---- */
        for (int tick = 0; tick < 20 && !g_stop; tick++) {
            int sx, sy;
            if (have_touch && touch_poll(&tp, &fb, &sx, &sy)) {
                if (!confirm) {
                    if (hit(&btn_restart, sx, sy)) { confirm = 1; confirm_at = now; }
                    else if (hit(&btn_reboot, sx, sy)) { confirm = 2; confirm_at = now; }
                } else {
                    if (hit(&btn_restart, sx, sy)) {
                        if (confirm == 1) {
                            int rc = system("/etc/init.d/S90odod restart >/dev/null 2>&1 || "
                                            "systemctl restart odod >/dev/null 2>&1");
                            (void)rc;
                        } else {
                            sync();
                            int rc = system("reboot");
                            (void)rc;
                        }
                    }
                    confirm = 0;
                }
                tick = 99;   /* redraw immediately after a tap */
            }
            struct timespec ts = { 0, 100 * 1000000L };
            nanosleep(&ts, NULL);
        }
    }

    return 0;
}
