/*
 * odo_ui.c — touch status panel for the odo-miner Cyclone V SoC.
 *
 * Renders a mining dashboard on the ILI9341 framebuffer (/dev/fb0, RGB565,
 * 320x240 with rotate=270 in the DTS) and handles the XPT2046 resistive
 * touch (/dev/input/event*, ads7846 driver) for two actions:
 *
 *     [RESTART MINER]  — restarts the odod/odo-miner service
 *     [REBOOT]         — reboots the board (with confirmation)
 *
 * Status comes from the JSON snapshot odo-miner writes on every heartbeat
 * (/run/odod/status.json). Parsing is deliberately primitive (strstr) — the
 * file is machine-generated by miner.c with known keys.
 *
 * Build: make            (in sw/odo-ui; cross-compile with CC=...-gcc)
 * Run:   odo-ui [status.json path]
 */

#define _POSIX_C_SOURCE 200809L
#define _DEFAULT_SOURCE     /* sync() */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <signal.h>
#include <dirent.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <ifaddrs.h>
#include <linux/fb.h>
#include <linux/input.h>

#include "odoui_gfx.h"

/* ------------------------------------------------------------------ */
/* TrueType font support via odoui_gfx.                               */
/* ------------------------------------------------------------------ */
#define FDIR "/etc/odo-ui/fonts/"
static gfx_font g_body;   /* labels + data        (IBM Plex Mono) */
static gfx_font g_head;   /* section headings     (Space Grotesk)   */
static gfx_font g_hero;   /* big metrics          (Space Grotesk)   */
static int ui_font_ready = 0;

typedef struct {
    int fd;
    uint16_t *pix;
    int w, h, stride;   /* stride in pixels */
} fb_t;

#define RGB565(r,g,b) (uint16_t)((((r)>>3)<<11) | (((g)>>2)<<5) | ((b)>>3))

static void fb_color565(uint16_t c, uint8_t *r, uint8_t *g, uint8_t *b)
{
    *r = (uint8_t)(((c >> 11) & 0x1F) * 255 / 31);
    *g = (uint8_t)(((c >> 5) & 0x3F) * 255 / 63);
    *b = (uint8_t)((c & 0x1F) * 255 / 31);
}

static int fb_init_fonts(void)
{
    if (ui_font_ready) return 0;
    if (gfx_font_load(&g_body, FDIR "IBMPlexMono-Medium.ttf", 16.0f) != 0 ||
        gfx_font_load(&g_head, FDIR "SpaceGrotesk-SemiBold.ttf", 22.0f) != 0 ||
        gfx_font_load(&g_hero, FDIR "SpaceGrotesk-SemiBold.ttf", 48.0f) != 0) {
        fprintf(stderr, "odo-ui: cannot load fonts from %s\n", FDIR);
        gfx_font_free(&g_body);
        gfx_font_free(&g_head);
        gfx_font_free(&g_hero);
        return -1;
    }
    ui_font_ready = 1;
    return 0;
}

static void fb_free_fonts(void)
{
    if (!ui_font_ready) return;
    gfx_font_free(&g_body);
    gfx_font_free(&g_head);
    gfx_font_free(&g_hero);
    ui_font_ready = 0;
}

/* Redesign palette: dark surfaces, gold accents, neutral text */
#define C_BG     RGB565(16, 15, 11)       /* page background          */
#define C_PANEL  RGB565(26, 24, 18)       /* header / card surface    */
#define C_TEXT   RGB565(242, 239, 230)
#define C_DIM    RGB565(172, 165, 144)
#define C_OK     RGB565(70, 200, 120)
#define C_WARN   RGB565(224, 123, 58)
#define C_BAD    RGB565(229, 86, 74)
#define C_ACCENT RGB565(240, 178, 60)     /* gold accent              */
#define C_BTN    C_PANEL
#define C_BTNHI  C_ACCENT

/* 16×16 hexagonal mark: outer ring (1=gold) + inner solid hex (2=gold).
 * Flat-top orientation matching the web SVG mark. */
static const char *logo_px[16] = {
    "................",   /* 0 */
    "....11111111....",   /* 1: outer top edge */
    "...1........1...",   /* 2 */
    "..1..........1..",   /* 3 */
    ".1....2222....1.",   /* 4: inner hex top */
    ".1...222222...1.",   /* 5 */
    "1...22222222...1",   /* 6 */
    "1...22222222...1",   /* 7 */
    "1...22222222...1",   /* 8 */
    ".1...222222...1.",   /* 9 */
    ".1....2222....1.",   /* 10: inner hex bottom */
    "..1..........1..",   /* 11 */
    "...1........1...",   /* 12 */
    "....11111111....",   /* 13: outer bottom edge */
    "................",   /* 14 */
    "................",   /* 15 */
};

static int fb_open(fb_t *fb)
{
    fb->fd = open("/dev/fb0", O_RDWR);
    if (fb->fd < 0) { perror("open /dev/fb0"); return -1; }

    struct fb_var_screeninfo v;
    struct fb_fix_screeninfo f;
    if (ioctl(fb->fd, FBIOGET_VSCREENINFO, &v) || ioctl(fb->fd, FBIOGET_FSCREENINFO, &f)) {
        perror("fb ioctl");
        return -1;
    }
    if (v.bits_per_pixel != 16) {
        fprintf(stderr, "expected 16bpp framebuffer, got %d\n", v.bits_per_pixel);
        return -1;
    }
    fb->w = (int)v.xres;
    fb->h = (int)v.yres;
    fb->stride = (int)(f.line_length / 2);
    fb->pix = mmap(NULL, (size_t)f.line_length * v.yres,
                   PROT_READ | PROT_WRITE, MAP_SHARED, fb->fd, 0);
    if (fb->pix == MAP_FAILED) { perror("mmap fb"); return -1; }

    /* Ensure the panel is unblanked (backlight on). fbtft ties the backlight
     * to the FB blank state, and the panel can come up blanked during boot —
     * so the boot splashes would draw but stay invisible. */
    int bfd = open("/sys/class/graphics/fb0/blank", O_WRONLY);
    if (bfd >= 0) { ssize_t w = write(bfd, "0\n", 2); (void)w; close(bfd); }
    return 0;
}

static void fb_rect(fb_t *fb, int x, int y, int w, int h, uint16_t c)
{
    if (x < 0) { w += x; x = 0; }
    if (y < 0) { h += y; y = 0; }
    if (x + w > fb->w) w = fb->w - x;
    if (y + h > fb->h) h = fb->h - y;
    for (int j = 0; j < h; j++) {
        uint16_t *row = fb->pix + (size_t)(y + j) * fb->stride + x;
        for (int i = 0; i < w; i++)
            row[i] = c;
    }
}

/* ------------------------------------------------------------------ */
/* Background image cache                                              */
/* ------------------------------------------------------------------ */
#define BG_PATH "/etc/odo-ui/bg.png"
static uint16_t *g_bg_cache = NULL;   /* heap-allocated 320×240 RGB565 */
static int       g_bg_ready = 0;

/* Load bg.png once into a pixel buffer. Call after fb_open. */
static void bg_load(fb_t *fb)
{
    if (g_bg_ready) return;
    size_t npix = (size_t)fb->w * fb->h;
    g_bg_cache = malloc(npix * sizeof(uint16_t));
    if (!g_bg_cache) return;
    /* Temporarily draw into the live framebuffer then snapshot it. */
    if (gfx_background((gfx_fb *)fb, BG_PATH, 10) == 0) {
        memcpy(g_bg_cache, fb->pix, npix * sizeof(uint16_t));
        g_bg_ready = 1;
    } else {
        free(g_bg_cache);
        g_bg_cache = NULL;
    }
}

/* Fill framebuffer with cached bg, or solid C_BG if no image. */
static void bg_blit(fb_t *fb)
{
    if (g_bg_ready && g_bg_cache)
        memcpy(fb->pix, g_bg_cache, (size_t)fb->w * fb->h * sizeof(uint16_t));
    else
        fb_rect(fb, 0, 0, fb->w, fb->h, C_BG);
}

/* Draw the shield logo at integer scale */
static void fb_logo(fb_t *fb, int x, int y, int scale)
{
    for (int r = 0; r < 16; r++) {
        for (int cidx = 0; cidx < 16; cidx++) {
            uint16_t col;
            switch (logo_px[r][cidx]) {
            case '1': col = C_ACCENT; break;
            case '2': col = C_ACCENT; break;
            case '3': col = RGB565(255, 255, 255); break;
            default: continue;
            }
            fb_rect(fb, x + cidx * scale, y + r * scale, scale, scale, col);
        }
    }
}

/* Draw text with integer scale; returns advance width */
static int fb_text(fb_t *fb, int x, int y, const char *s, int scale, uint16_t c)
{
    if (!ui_font_ready)
        return (int)strlen(s) * 8 * scale;

    gfx_font *font = scale >= 3 ? &g_hero : scale == 2 ? &g_head : &g_body;
    uint8_t r, g, b;
    fb_color565(c, &r, &g, &b);
    gfx_text((gfx_fb *)fb, font, x, y, s, r, g, b);
    return gfx_text_w(font, s);
}

static int fb_text_w(int scale, const char *s)
{
    if (!ui_font_ready)
        return (int)strlen(s) * 8 * scale;

    gfx_font *font = scale >= 3 ? &g_hero : scale == 2 ? &g_head : &g_body;
    return gfx_text_w(font, s);
}

/* ------------------------------------------------------------------ */
/* Touch input (ads7846)                                               */
/* ------------------------------------------------------------------ */
typedef struct {
    int fd;
    int raw_x, raw_y, down;
    int cur_x, cur_y;                /* live mapped position while pressed */
    int press_x, press_y;           /* screen coords at the moment touch went down */
    int min_x, max_x, min_y, max_y;  /* raw calibration */
    int swap_xy, inv_x, inv_y;
    int _was_down, _last_x, _last_y; /* internal poll state (replaces function statics) */
} touch_t;

static int touch_open(touch_t *t)
{
    memset(t, 0, sizeof(*t));
    t->fd = -1;
    t->min_x = 150; t->max_x = 3900;
    t->min_y = 150; t->max_y = 3900;
    /* Panel is rotate=270 in the DTS, so the touch axes are swapped relative
     * to the display, and Y is inverted. (Calibrated on hardware: finger
     * top-left -> screen top-left with swap_xy + inv_y.) */
    t->swap_xy = 1;
    t->inv_y = 1;

    DIR *d = opendir("/dev/input");
    if (!d) return -1;
    struct dirent *e;
    char path[300], name[128];
    while ((e = readdir(d))) {
        if (strncmp(e->d_name, "event", 5) != 0) continue;
        snprintf(path, sizeof(path), "/dev/input/%s", e->d_name);
        int fd = open(path, O_RDONLY | O_NONBLOCK);
        if (fd < 0) continue;
        name[0] = 0;
        ioctl(fd, EVIOCGNAME(sizeof(name)), name);
        if (strstr(name, "ADS7846") || strstr(name, "ads7846")) {
            t->fd = fd;
            break;
        }
        close(fd);
    }
    closedir(d);
    return t->fd >= 0 ? 0 : -1;
}

/* Pump events; returns 1 on a fresh "tap" (release), with screen coords.
 * t->press_x/press_y hold the position where the touch started, so the caller
 * can distinguish a tap (sx ≈ press_x) from a horizontal swipe (|sx−press_x| > threshold). */
static int touch_poll(touch_t *t, fb_t *fb, int *sx, int *sy)
{
    if (t->fd < 0) return 0;
    struct input_event ev;
    int tapped = 0;

    while (read(t->fd, &ev, sizeof(ev)) == (ssize_t)sizeof(ev)) {
        if (ev.type == EV_ABS) {
            if (ev.code == ABS_X) t->raw_x = ev.value;
            if (ev.code == ABS_Y) t->raw_y = ev.value;
        } else if (ev.type == EV_KEY && ev.code == BTN_TOUCH) {
            t->down = ev.value;
        } else if (ev.type == EV_SYN) {
            if (t->down) {
                int rx = t->raw_x, ry = t->raw_y;
                if (t->swap_xy) { int tmp = rx; rx = ry; ry = tmp; }
                long px = (long)(rx - t->min_x) * fb->w / (t->max_x - t->min_x);
                long py = (long)(ry - t->min_y) * fb->h / (t->max_y - t->min_y);
                if (t->inv_x) px = fb->w - 1 - px;
                if (t->inv_y) py = fb->h - 1 - py;
                if (px < 0) px = 0;
                if (px >= fb->w) px = fb->w - 1;
                if (py < 0) py = 0;
                if (py >= fb->h) py = fb->h - 1;
                if (!t->_was_down) {
                    t->press_x = (int)px;
                    t->press_y = (int)py;
                }
                t->_last_x = (int)px;
                t->_last_y = (int)py;
                t->cur_x   = (int)px;
                t->cur_y   = (int)py;
                t->_was_down = 1;
            } else if (t->_was_down) {
                t->_was_down = 0;
                *sx = t->_last_x;
                *sy = t->_last_y;
                tapped = 1;
            }
        }
    }
    return tapped;
}

/* ------------------------------------------------------------------ */
/* Status file                                                         */
/* ------------------------------------------------------------------ */
typedef struct {
    char   pool[160];
    char   job_id[64];
    int    connected;
    long   epoch;
    long   epoch_next;       /* unix time of the next Odo shapechange */
    double hashrate;
    long long shares_found, shares_submitted;
    long   last_share, uptime, updated;
    double best_diff_session, best_diff_alltime;
    long long blocks_found;
    long   last_block;
    long   temp_c;      /* DS18B20 reading, -1 = no sensor/no reading yet */
    long   fan_duty_pct; /* commanded fan speed, 0-100 (%) */
    long   fan_rpm;      /* -1 = no tach */
    long long shares_accepted;
    long long shares_rejected;
    long   bitstream_epoch;
    char   backend[16];
} status_t;

static long json_long(const char *buf, const char *key, long def)
{
    char pat[64];
    snprintf(pat, sizeof(pat), "\"%s\":", key);
    const char *p = strstr(buf, pat);
    return p ? strtol(p + strlen(pat), NULL, 10) : def;
}

static double json_double(const char *buf, const char *key, double def)
{
    char pat[64];
    snprintf(pat, sizeof(pat), "\"%s\":", key);
    const char *p = strstr(buf, pat);
    return p ? strtod(p + strlen(pat), NULL) : def;
}

static void json_string(const char *buf, const char *key, char *out, size_t out_sz)
{
    char pat[64];
    snprintf(pat, sizeof(pat), "\"%s\": \"", key);
    const char *p = strstr(buf, pat);
    out[0] = 0;
    if (!p) return;
    p += strlen(pat);
    size_t i = 0;
    while (*p && *p != '"' && i + 1 < out_sz)
        out[i++] = *p++;
    out[i] = 0;
}

static int status_read(const char *path, status_t *s)
{
    char buf[2048];
    FILE *f = fopen(path, "r");
    if (!f) return -1;
    size_t n = fread(buf, 1, sizeof(buf) - 1, f);
    fclose(f);
    buf[n] = 0;

    json_string(buf, "pool", s->pool, sizeof(s->pool));
    json_string(buf, "job_id", s->job_id, sizeof(s->job_id));
    s->connected        = strstr(buf, "\"connected\": true") != NULL;
    s->epoch            = json_long(buf, "epoch", 0);
    s->epoch_next       = json_long(buf, "epoch_next", 0);
    s->hashrate         = json_double(buf, "hashrate", 0);
    s->shares_found       = json_long(buf, "shares_found", 0);
    s->shares_submitted   = json_long(buf, "shares_submitted", 0);
    s->last_share         = json_long(buf, "last_share", 0);
    s->best_diff_session  = json_double(buf, "best_diff_session", 0.0);
    s->best_diff_alltime  = json_double(buf, "best_diff_alltime", 0.0);
    s->blocks_found        = json_long(buf, "blocks_found", 0);
    s->last_block          = json_long(buf, "last_block", 0);
    s->temp_c              = json_long(buf, "temp_c", -1);
    s->fan_duty_pct        = json_long(buf, "fan_duty_pct", 0);
    s->fan_rpm             = json_long(buf, "fan_rpm", -1);
    s->shares_accepted     = json_long(buf, "shares_accepted", 0);
    s->shares_rejected     = json_long(buf, "shares_rejected", 0);
    s->bitstream_epoch     = json_long(buf, "bitstream_epoch", 0);
    json_string(buf, "backend", s->backend, sizeof(s->backend));
    s->uptime             = json_long(buf, "uptime", 0);
    s->updated            = json_long(buf, "updated", 0);
    return 0;
}

/* -----------------------------------------------------------------------
 * Block-found banner: stays acknowledged across odo-ui restarts (a tap
 * clears it on screen AND on disk). Defaults to the daemon's current
 * blocks_found on first-ever run so an upgrade doesn't retroactively
 * celebrate history -- only NEW finds from here on trigger the banner.
 * ---------------------------------------------------------------------- */
#define BLOCK_ACK_PATH "/var/lib/odod/ui_block_ack"

static long long block_ack_load(long long fallback)
{
    FILE *f = fopen(BLOCK_ACK_PATH, "r");
    if (!f) return fallback;
    long long v = fallback;
    if (fscanf(f, "%lld", &v) != 1) v = fallback;
    fclose(f);
    return v;
}

static void block_ack_save(long long v)
{
    FILE *f = fopen(BLOCK_ACK_PATH ".tmp", "w");
    if (!f) return;
    fprintf(f, "%lld\n", v);
    fclose(f);
    rename(BLOCK_ACK_PATH ".tmp", BLOCK_ACK_PATH);
}

/* ------------------------------------------------------------------ */
/* UI                                                                  */
/* ------------------------------------------------------------------ */
typedef struct { int x, y, w, h; } rect_t;

static int hit(const rect_t *r, int x, int y)
{
    return x >= r->x && x < r->x + r->w && y >= r->y && y < r->y + r->h;
}

static void fmt_rate(double hps, char *out, size_t sz)
{
    if (hps >= 1e6)      snprintf(out, sz, "%.2f MH/s", hps / 1e6);
    else if (hps >= 1e3) snprintf(out, sz, "%.1f kH/s", hps / 1e3);
    else                 snprintf(out, sz, "%.0f H/s", hps);
}

static void fmt_age(long secs, char *out, size_t sz)
{
    if (secs < 0)            snprintf(out, sz, "never");
    else if (secs < 60)      snprintf(out, sz, "%lds ago", secs);
    else if (secs < 3600)    snprintf(out, sz, "%ldm ago", secs / 60);
    else                     snprintf(out, sz, "%ldh ago", secs / 3600);
}

static void fmt_diff(double d, char *out, size_t sz)
{
    if (d <= 0.0)        snprintf(out, sz, "-");
    else if (d >= 1e9)   snprintf(out, sz, "%.2fG", d / 1e9);
    else if (d >= 1e6)   snprintf(out, sz, "%.2fM", d / 1e6);
    else if (d >= 1e3)   snprintf(out, sz, "%.2fK", d / 1e3);
    else if (d >= 1.0)   snprintf(out, sz, "%.3f",  d);
    else                 snprintf(out, sz, "%.5f",  d);
}

/* First non-loopback IPv4 — shown on screen so the web UI is findable */
static void board_ip(char *ip, size_t ip_sz)
{
    ip[0] = 0;
    struct ifaddrs *ifa0 = NULL;
    if (getifaddrs(&ifa0) != 0)
        return;
    for (struct ifaddrs *ifa = ifa0; ifa; ifa = ifa->ifa_next) {
        if (!ifa->ifa_addr || ifa->ifa_addr->sa_family != AF_INET)
            continue;
        if (strcmp(ifa->ifa_name, "lo") == 0)
            continue;
        inet_ntop(AF_INET, &((struct sockaddr_in *)ifa->ifa_addr)->sin_addr,
                  ip, ip_sz);
        break;
    }
    freeifaddrs(ifa0);
}

/* Connected WiFi SSID + signal (dBm) via `iw`. ssid empty if not associated. */
static void wifi_status(char *ssid, size_t sz, int *dbm)
{
    ssid[0] = 0; *dbm = 0;
    FILE *p = popen("iw dev wlan0 link 2>/dev/null", "r");
    if (!p) return;
    char line[200], *s;
    while (fgets(line, sizeof line, p)) {
        if ((s = strstr(line, "SSID: "))) {
            strncpy(ssid, s + 6, sz - 1); ssid[sz - 1] = 0;
            ssid[strcspn(ssid, "\r\n")] = 0;
        } else if ((s = strstr(line, "signal: "))) {
            *dbm = atoi(s + 8);            /* e.g. "signal: -55 dBm" */
        }
    }
    pclose(p);
}

/* 4-bar signal-strength icon from a dBm value (0 = unknown/not connected). */
static void fb_signal(fb_t *fb, int x, int y, int dbm, uint16_t on, uint16_t off)
{
    int level = dbm == 0 ? 0 :
                dbm >= -55 ? 4 : dbm >= -65 ? 3 :
                dbm >= -75 ? 2 : dbm >= -85 ? 1 : 0;
    for (int i = 0; i < 4; i++) {
        int h = 3 + i * 2;                 /* heights 3,5,7,9 */
        fb_rect(fb, x + i * 4, y + (9 - h), 3, h, i < level ? on : off);
    }
}

/* ------------------------------------------------------------------ */
/* WiFi setup: on-screen keyboard -> /etc/wpa_supplicant.conf          */
/* ------------------------------------------------------------------ */
#define WPA_CONF "/etc/wpa_supplicant.conf"

enum { KC_CHAR = 0, KC_SHIFT, KC_BKSP, KC_SPACE, KC_SAVE, KC_CANCEL };

typedef struct {
    rect_t r;
    int kind;          /* KC_* */
    char lo, up;       /* characters for KC_CHAR */
    const char *label; /* for non-char keys */
} kbkey_t;

/* Build the keyboard layout for a given framebuffer width. Returns key count. */
static int kb_build(kbkey_t *k, int fbw)
{
    static const char *R0 = "1234567890", *R0U = "!@#$%^&*()";
    static const char *R1 = "qwertyuiop", *R1U = "QWERTYUIOP";
    static const char *R2 = "asdfghjkl",  *R2U = "ASDFGHJKL";
    static const char *R3 = "zxcvbnm",    *R3U = "ZXCVBNM";
    int n = 0, cw = fbw / 10, kh = 26, top = 84, pitch = 30;

    for (int i = 0; i < 10; i++)
        k[n++] = (kbkey_t){ {i*cw+1, top,          cw-2, kh}, KC_CHAR, R0[i], R0U[i], 0 };
    for (int i = 0; i < 10; i++)
        k[n++] = (kbkey_t){ {i*cw+1, top+pitch,    cw-2, kh}, KC_CHAR, R1[i], R1U[i], 0 };
    for (int i = 0; i < 9; i++)
        k[n++] = (kbkey_t){ {i*cw+cw/2+1, top+2*pitch, cw-2, kh}, KC_CHAR, R2[i], R2U[i], 0 };

    int y3 = top + 3*pitch;
    k[n++] = (kbkey_t){ {1, y3, 46, kh}, KC_SHIFT, 0, 0, "SHFT" };
    for (int i = 0; i < 7; i++)
        k[n++] = (kbkey_t){ {49+i*cw, y3, cw-2, kh}, KC_CHAR, R3[i], R3U[i], 0 };
    k[n++] = (kbkey_t){ {49+7*cw, y3, fbw-(49+7*cw)-1, kh}, KC_BKSP, 0, 0, "DEL" };

    int y4 = top + 4*pitch;
    k[n++] = (kbkey_t){ {1,   y4, 30, kh}, KC_CHAR, '-', '-', 0 };
    k[n++] = (kbkey_t){ {33,  y4, 30, kh}, KC_CHAR, '_', '_', 0 };
    k[n++] = (kbkey_t){ {65,  y4, 30, kh}, KC_CHAR, '.', '.', 0 };
    k[n++] = (kbkey_t){ {97,  y4, 92, kh}, KC_SPACE,  0, 0, "SPACE" };
    k[n++] = (kbkey_t){ {191, y4, 60, kh}, KC_SAVE,   0, 0, "SAVE" };
    k[n++] = (kbkey_t){ {253, y4, fbw-253-1, kh}, KC_CANCEL, 0, 0, "CXL" };
    return n;
}

/* 9x7 eye icon — password reveal toggle */
static void fb_eye(fb_t *fb, int x, int y, uint16_t c)
{
    static const char *eye[7] = {
        "...111...", ".11...11.", "1..111..1",
        "1.11111.1", "1..111..1", ".11...11.", "...111...",
    };
    for (int r = 0; r < 7; r++)
        for (int i = 0; i < 9; i++)
            if (eye[r][i] == '1') fb_rect(fb, x + i, y + r, 1, 1, c);
}

#define EYE_W 24
static void wifi_draw(fb_t *fb, const kbkey_t *k, int nk, const char *ssid,
                      const char *psk, int field, int shift, int reveal)
{
    bg_blit(fb);
    gfx_rect_a((gfx_fb *)fb, 0, 0, fb->w, 30, 26, 24, 18, 210);
    fb_logo(fb, 6, 4, 1);
    fb_text(fb, 26, 8, "WIFI SETUP", 2, C_TEXT);

    char ln[200];
    /* SSID field (active one highlighted) */
    fb_rect(fb, 6, 34, fb->w - 12, 18, field == 0 ? C_ACCENT : C_PANEL);
    snprintf(ln, sizeof ln, "SSID: %s%s", ssid, (field == 0 ? "_" : ""));
    fb_text(fb, 10, 37, ln, 1, field == 0 ? C_BG : C_TEXT);
    /* PSK field (leaves room on the right for the eye toggle) */
    fb_rect(fb, 6, 56, fb->w - 12 - EYE_W, 18, field == 1 ? C_ACCENT : C_PANEL);
    if (reveal) {
        snprintf(ln, sizeof ln, "PSK:  %s%s", psk, (field == 1 ? "_" : ""));
    } else {
        size_t L = strlen(psk); char mask[160];
        for (size_t i = 0; i < L && i < sizeof(mask) - 2; i++) mask[i] = '*';
        mask[L < sizeof(mask) - 2 ? L : sizeof(mask) - 2] = 0;
        snprintf(ln, sizeof ln, "PSK:  %s%s", mask, (field == 1 ? "_" : ""));
    }
    fb_text(fb, 10, 59, ln, 1, C_TEXT);
    /* eye toggle (bright when revealed) */
    fb_rect(fb, fb->w - 6 - EYE_W, 56, EYE_W, 18, C_PANEL);
    fb_eye(fb, fb->w - 6 - EYE_W + 7, 61, reveal ? C_ACCENT : C_DIM);

    for (int i = 0; i < nk; i++) {
        const kbkey_t *key = &k[i];
        uint16_t inner = C_PANEL;
        uint16_t text = C_TEXT;
        if (key->kind == KC_SAVE) { inner = C_ACCENT; text = C_BG; }
        else if (key->kind == KC_CANCEL) { inner = C_BAD; }
        else if (key->kind == KC_SHIFT && shift) { inner = C_ACCENT; text = C_BG; }
        fb_rect(fb, key->r.x, key->r.y, key->r.w, key->r.h, C_PANEL);
        fb_rect(fb, key->r.x + 1, key->r.y + 1, key->r.w - 2, key->r.h - 2, inner);
        char lab[8]; const char *s;
        if (key->kind == KC_CHAR) { lab[0] = shift ? key->up : key->lo; lab[1] = 0; s = lab; }
        else s = key->label;
        fb_text(fb, key->r.x + (key->r.w - fb_text_w(1, s)) / 2,
                key->r.y + (key->r.h - 12) / 2, s, 1, text);
    }
}

/* Apply a tap. Returns 0 stay, 1 save requested, 2 cancel. */
static int wifi_tap(int sx, int sy, const kbkey_t *k, int nk,
                    char *ssid, size_t ssz, char *psk, size_t psz,
                    int *field, int *shift)
{
    if (sy >= 34 && sy < 52) { *field = 0; return 0; }
    if (sy >= 56 && sy < 74) { *field = 1; return 0; }
    for (int i = 0; i < nk; i++) {
        if (!hit(&k[i].r, sx, sy)) continue;
        char *buf = *field == 0 ? ssid : psk;
        size_t sz = *field == 0 ? ssz : psz, L = strlen(buf);
        switch (k[i].kind) {
        case KC_CHAR:  if (L + 1 < sz) { buf[L] = *shift ? k[i].up : k[i].lo; buf[L+1] = 0; }
                       *shift = 0; break;
        case KC_SHIFT: *shift = !*shift; break;
        case KC_BKSP:  if (L > 0) buf[L-1] = 0; break;
        case KC_SPACE: if (L + 1 < sz) { buf[L] = ' '; buf[L+1] = 0; } break;
        case KC_SAVE:  return 1;
        case KC_CANCEL:return 2;
        }
        return 0;
    }
    return 0;
}

static void wifi_save(const char *ssid, const char *psk)
{
    FILE *f = fopen(WPA_CONF, "w");
    if (!f) return;
    /* ctrl_interface in /tmp (not /var/run, which doesn't exist here) */
    fprintf(f, "ctrl_interface=/tmp/wpa_supplicant\nupdate_config=1\ncountry=GB\n"
               "network={\n\tssid=\"%s\"\n", ssid);
    if (psk[0]) fprintf(f, "\tpsk=\"%s\"\n", psk);
    else        fprintf(f, "\tkey_mgmt=NONE\n");
    fprintf(f, "}\n");
    fclose(f);
    sync();
    int rc = system("/etc/init.d/S45wifi restart >/dev/null 2>&1 &");
    (void)rc;
}

/* Scan nearby networks via `iw`. Returns count; fills list[][33] (deduped). */
static int wifi_scan(char list[][33], int max)
{
    FILE *p = popen("iw dev wlan0 scan 2>/dev/null | sed -n 's/^[\t ]*SSID: //p'", "r");
    if (!p) return 0;
    int n = 0; char line[80];
    while (n < max && fgets(line, sizeof line, p)) {
        line[strcspn(line, "\r\n")] = 0;
        if (!line[0]) continue;                 /* skip hidden SSIDs */
        int dup = 0;
        for (int i = 0; i < n; i++) if (!strcmp(list[i], line)) { dup = 1; break; }
        if (!dup) {
            size_t len = strlen(line);
            if (len >= sizeof list[n]) len = sizeof list[n] - 1;
            memcpy(list[n], line, len);
            list[n][len] = '\0';
            n++;
        }
    }
    pclose(p);
    return n;
}

#define SCAN_ROW_H 22
#define SCAN_ROW_Y0 36
static void scan_draw(fb_t *fb, char list[][33], int n)
{
    bg_blit(fb);
    gfx_rect_a((gfx_fb *)fb, 0, 0, fb->w, 30, 26, 24, 18, 210);
    fb_text(fb, 8, 8, "SELECT NETWORK", 2, C_TEXT);
    int rows = n > 8 ? 8 : n;
    for (int i = 0; i < rows; i++) {
        int y = SCAN_ROW_Y0 + i * SCAN_ROW_H;
        fb_rect(fb, 6, y, fb->w - 12, SCAN_ROW_H - 2, C_PANEL);
        fb_text(fb, 12, y + 5, list[i], 1, C_TEXT);
    }
    fb_rect(fb, 6, fb->h - 24, fb->w - 12, 20, C_PANEL);
    fb_text(fb, 12, fb->h - 18,
            n ? "tap a network, or here to type it" : "no networks - tap here to type",
            1, C_TEXT);
}

static volatile sig_atomic_t g_stop = 0;
static void on_sig(int s) { (void)s; g_stop = 1; }

/* ------------------------------------------------------------------ */
/* Screen settings (dim timeout + dim level)                           */
/* ------------------------------------------------------------------ */
#define UI_CONF_PATH         "/etc/odo-ui.conf"
#define DIM_TIMEOUT_DEFAULT  300  /* seconds; 0 = never */
#define DIM_LEVEL_DEFAULT    0    /* 0 = full blank, 1-100 = dim to % */

static int    g_dim_timeout   = DIM_TIMEOUT_DEFAULT;
static int    g_dim_level     = DIM_LEVEL_DEFAULT;
static time_t g_last_activity = 0;
static int    g_blanked       = 0;

static void load_ui_conf(void)
{
    FILE *f = fopen(UI_CONF_PATH, "r");
    if (!f) return;
    char line[128];
    while (fgets(line, sizeof(line), f)) {
        char *eq = strchr(line, '=');
        if (!eq || line[0] == '#') continue;
        *eq = 0;
        int val = atoi(eq + 1);
        if      (strcmp(line, "DIM_TIMEOUT") == 0) g_dim_timeout = val < 0 ? 0 : val > 3600 ? 3600 : val;
        else if (strcmp(line, "DIM_LEVEL")   == 0) g_dim_level   = val < 0 ? 0 : val > 100  ? 100  : val;
    }
    fclose(f);
}

static void save_ui_conf(void)
{
    FILE *f = fopen(UI_CONF_PATH ".tmp", "w");
    if (!f) return;
    fprintf(f, "DIM_TIMEOUT=%d\nDIM_LEVEL=%d\n", g_dim_timeout, g_dim_level);
    fclose(f);
    rename(UI_CONF_PATH ".tmp", UI_CONF_PATH);
}

static void fb_set_blank(int blank)
{
    /* fbtft ties /sys/class/graphics/fb0/blank to the ILI9341 display-on/off
     * command — writing "1" turns the panel off cleanly without wiping the
     * framebuffer, so the next unblank instantly restores the last frame. */
    int fd = open("/sys/class/graphics/fb0/blank", O_WRONLY);
    if (fd < 0) return;
    ssize_t w = write(fd, blank ? "1\n" : "0\n", 2);
    (void)w;
    close(fd);
}

/* Software dim: scale every RGB565 pixel to pct% brightness (1-100). */
static void fb_apply_dim(fb_t *fb, int pct)
{
    int n = fb->w * fb->h;
    for (int i = 0; i < n; i++) {
        uint16_t p = fb->pix[i];
        int r = ((p >> 11) & 0x1F) * pct / 100;
        int g = ((p >>  5) & 0x3F) * pct / 100;
        int b = ( p        & 0x1F) * pct / 100;
        fb->pix[i] = (uint16_t)((r << 11) | (g << 5) | b);
    }
}

/* Full WiFi setup screen loop: keyboard + scan list. Returns when the user
 * saves (writes wpa_supplicant.conf) or cancels. */
static void run_wifi_setup(fb_t *fb, touch_t *tp, const kbkey_t *keys, int nk, int have_touch)
{
    char ssid[64] = "", psk[128] = "";
    int field = 0, shift = 0, scan_mode = 0, scan_n = 0, reveal = 0;
    char scan[16][33];
    rect_t scan_btn = { fb->w - 52, 7, 46, 16 };
    rect_t eye_btn  = { fb->w - 6 - EYE_W, 56, EYE_W, 18 };

    while (!g_stop) {
        if (scan_mode) {
            scan_draw(fb, scan, scan_n);
        } else {
            wifi_draw(fb, keys, nk, ssid, psk, field, shift, reveal);
            fb_rect(fb, scan_btn.x, scan_btn.y, scan_btn.w, scan_btn.h, C_ACCENT);
            fb_text(fb, scan_btn.x + (scan_btn.w - fb_text_w(1, "SCAN")) / 2,
                    scan_btn.y + (scan_btn.h - 12) / 2, "SCAN", 1, C_BG);
        }
        for (int tick = 0; tick < 20 && !g_stop; tick++) {
            int sx, sy;
            if (have_touch && touch_poll(tp, fb, &sx, &sy)) {
                if (scan_mode) {
                    int rows = scan_n > 8 ? 8 : scan_n;
                    for (int i = 0; i < rows; i++) {
                        rect_t r = { 6, SCAN_ROW_Y0 + i * SCAN_ROW_H, fb->w - 12, SCAN_ROW_H - 2 };
                        if (hit(&r, sx, sy)) {
                            strncpy(ssid, scan[i], sizeof ssid - 1);
                            ssid[sizeof ssid - 1] = 0;
                            field = 1;       /* jump to password entry */
                            break;
                        }
                    }
                    scan_mode = 0;           /* any tap returns to the keyboard */
                } else if (hit(&scan_btn, sx, sy)) {
                    fb_rect(fb, 0, fb->h / 2 - 10, fb->w, 20, C_PANEL);
                    fb_text(fb, fb->w / 2 - 44, fb->h / 2 - 4, "Scanning...", 1, C_TEXT);
                    scan_n = wifi_scan(scan, 16);
                    scan_mode = 1;
                } else if (hit(&eye_btn, sx, sy)) {
                    reveal = !reveal;             /* toggle password reveal */
                } else {
                    int r = wifi_tap(sx, sy, keys, nk, ssid, sizeof ssid,
                                     psk, sizeof psk, &field, &shift);
                    if (r == 1) { wifi_save(ssid, psk); return; }
                    if (r == 2) return;
                }
                tick = 99;
            }
            struct timespec ts = { 0, 100 * 1000000L };
            nanosleep(&ts, NULL);
        }
    }
}

/* ---- Glance screen: big hashrate hero + shapechange countdown + bar ---- */
static void draw_glance(fb_t *fb, const status_t *st, time_t now,
                        const char *wssid, int wdbm)
{
    (void)wssid; (void)wdbm;
    bg_blit(fb);
    /* header */
    gfx_rect_a((gfx_fb *)fb, 0, 0, fb->w, 36, 26, 24, 18, 210);
    fb_rect(fb, 0, 36, fb->w, 2, C_ACCENT);
    fb_logo(fb, 6, 2, 2);
    fb_text(fb, 44, 10, "ODO MINER", 2, C_TEXT);
    /* status pill, right-aligned */
    {
        const char *txt; uint16_t col;
        int stale = !st->updated || (now - (time_t)st->updated > 120);
        if (stale)              { txt = "MINER DOWN"; col = C_BAD; }
        else if (st->connected) { txt = "POOL OK";    col = C_OK; }
        else                    { txt = "OFFLINE";    col = C_WARN; }
        int pw = fb_text_w(1, txt) + 12;
        fb_rect(fb, fb->w - pw - 6, 10, pw, 16, C_BG);
        fb_text(fb, fb->w - pw, 14, txt, 1, col);
    }
    /* hashrate hero */
    char rate[48];
    fb_text(fb, 14, 42, "HASHRATE", 1, C_DIM);
    fmt_rate(st->hashrate, rate, sizeof(rate));
    fb_text(fb, 14, 54, rate, 3, C_TEXT);
    /* shapechange countdown + progress bar */
    fb_text(fb, 14, 110, "SHAPECHANGE IN", 1, C_DIM);
    if (st->epoch && st->epoch_next > (long)st->epoch) {
        long left = (long)st->epoch_next - now;
        if (left < 0) left = 0;
        char cntdn[32];
        snprintf(cntdn, sizeof(cntdn), "%ldd %ldh %ldm",
                 left / 86400, (left % 86400) / 3600, (left % 3600) / 60);
        fb_text(fb, 14, 122, cntdn, 2, C_TEXT);
        long bar_total = (long)st->epoch_next - (long)st->epoch;
        long bar_done  = now - (long)st->epoch;
        if (bar_done < 0) bar_done = 0;
        int bar_full = fb->w - 28;
        int bar_fill = (bar_total > 0) ? (int)((long)bar_full * bar_done / bar_total) : 0;
        if (bar_fill > bar_full) bar_fill = bar_full;
        fb_rect(fb, 14, 148, bar_full, 7, C_PANEL);
        if (bar_fill > 0) fb_rect(fb, 14, 148, bar_fill, 7, C_ACCENT);
    } else {
        fb_text(fb, 14, 122, "loading...", 1, C_DIM);
        fb_rect(fb, 14, 148, fb->w - 28, 7, C_PANEL);
    }
    /* Epoch mismatch warning OR compact summary (shares + best-diff, then health) */
    if (st->bitstream_epoch && st->epoch && st->bitstream_epoch != st->epoch) {
        fb_rect(fb, 6, 158, fb->w - 12, 18, C_BAD);
        const char *wt = "! WRONG EPOCH - REBOOT !";
        fb_text(fb, (fb->w - fb_text_w(1, wt)) / 2, 161, wt, 1, C_TEXT);
    } else {
        char val[40];
        /* Line 1: accepted-share count + best difficulty (this session) */
        char ds[20];
        fmt_diff(st->best_diff_session, ds, sizeof(ds));
        fb_text(fb, 14, 160, "SHARES", 1, C_DIM);
        snprintf(val, sizeof(val), "%lld", st->shares_accepted);
        fb_text(fb, 68, 160, val, 1, C_TEXT);
        fb_text(fb, 168, 160, "BEST-S", 1, C_DIM);
        fb_text(fb, 222, 160, ds, 1, C_ACCENT);
        /* Line 2: compact health — temp, accept-rate, fan */
        long long total = st->shares_accepted + st->shares_rejected;
        if (st->temp_c >= -50 && st->temp_c <= 150) {
            snprintf(val, sizeof(val), "%ldC", st->temp_c);
            fb_text(fb, 14, 176, "TEMP", 1, C_DIM);
            fb_text(fb, 54, 176, val, 1, st->temp_c >= 65 ? C_WARN : C_TEXT);
        }
        if (total > 0) {
            int pct = (int)(st->shares_accepted * 100LL / total);
            snprintf(val, sizeof(val), "%d%%", pct);
            fb_text(fb, 120, 176, "ACC", 1, C_DIM);
            fb_text(fb, 150, 176, val, 1,
                    pct >= 90 ? C_OK : pct >= 70 ? C_WARN : C_BAD);
        }
        if (st->fan_rpm >= 0) {
            snprintf(val, sizeof(val), "%ld%%", st->fan_duty_pct);
            fb_text(fb, 220, 176, "FAN", 1, C_DIM);
            fb_text(fb, 250, 176, val, 1, st->fan_duty_pct > 0 ? C_OK : C_DIM);
        }
    }
}

/* ---- Detail screen: expanded key/value stat rows ---- */
static void draw_detail(fb_t *fb, const status_t *st, time_t now,
                        const char *wssid, int wdbm)
{
    bg_blit(fb);
    /* header */
    gfx_rect_a((gfx_fb *)fb, 0, 0, fb->w, 36, 26, 24, 18, 210);
    fb_rect(fb, 0, 36, fb->w, 2, C_ACCENT);
    fb_logo(fb, 6, 2, 2);
    fb_text(fb, 44, 10, "DETAILS", 2, C_TEXT);
    if (wssid[0]) fb_signal(fb, fb->w - 24, 14, wdbm, C_OK, C_PANEL);
    /* stat rows */
    int y = 44;
    int xL = 14, xLv = 68, xR = 168, xRv = 216;
    char val[80], age[24];

    fb_text(fb, xL, y, "POOL",   1, C_DIM);
    fb_text(fb, xLv, y, st->pool[0] ? st->pool : "?", 1, C_TEXT);
    y += 14;

    fb_text(fb, xL, y, "JOB",    1, C_DIM);
    fb_text(fb, xLv, y, st->job_id[0] ? st->job_id : "-", 1, C_TEXT);
    fb_text(fb, xR, y, "SBM/FND", 1, C_DIM);
    snprintf(val, sizeof(val), "%lld/%lld", st->shares_submitted, st->shares_found);
    fb_text(fb, xRv, y, val, 1, C_TEXT);
    y += 14;

    fb_text(fb, xL, y, "UPTIME", 1, C_DIM);
    snprintf(val, sizeof(val), "%ldh %ldm", st->uptime / 3600, (st->uptime % 3600) / 60);
    fb_text(fb, xLv, y, val, 1, C_TEXT);
    fb_text(fb, xR, y, "LAST",   1, C_DIM);
    fmt_age(st->last_share ? now - (time_t)st->last_share : -1L, age, sizeof(age));
    fb_text(fb, xRv, y, age, 1, C_TEXT);
    y += 14;

    char ip[64];
    board_ip(ip, sizeof(ip));
    fb_text(fb, xL, y, "IP",     1, C_DIM);
    fb_text(fb, xLv, y, ip[0] ? ip : "no network", 1, ip[0] ? C_TEXT : C_WARN);
    y += 14;

    {
        char wsh[26];
        snprintf(wsh, sizeof(wsh), "%s", wssid[0] ? wssid : "-");
        fb_text(fb, xL, y, "WIFI",   1, C_DIM);
        fb_text(fb, xLv, y, wsh, 1, wssid[0] ? C_TEXT : C_DIM);
        if (wssid[0]) fb_signal(fb, fb->w - 24, y, wdbm, C_OK, C_PANEL);
    }
    y += 14;

    fb_text(fb, xL, y, "EPOCH",  1, C_DIM);
    if (st->epoch && st->epoch_next && now >= st->epoch_next) {
        snprintf(val, sizeof(val), "%ld  ROLLING", st->epoch);
        fb_text(fb, xLv, y, val, 1, C_WARN);
    } else if (st->epoch && st->epoch_next > now) {
        long left = (long)st->epoch_next - now;
        snprintf(val, sizeof(val), "%ld (%ldd %ldh)", st->epoch,
                 left / 86400, (left % 86400) / 3600);
        fb_text(fb, xLv, y, val, 1, C_TEXT);
    } else {
        snprintf(val, sizeof(val), "%ld", st->epoch);
        fb_text(fb, xLv, y, val, 1, st->epoch ? C_TEXT : C_DIM);
    }
    y += 14;

    /* Best difficulty: session (since miner start) and all-time (persisted) */
    char ds[20], da[20];
    fmt_diff(st->best_diff_session, ds, sizeof(ds));
    fmt_diff(st->best_diff_alltime, da, sizeof(da));
    fb_text(fb, xL, y, "BEST-S", 1, C_DIM);
    fb_text(fb, xLv, y, ds, 1, C_ACCENT);
    fb_text(fb, xR, y, "BEST-A", 1, C_DIM);
    fb_text(fb, xRv, y, da, 1, C_ACCENT);
    y += 14;

    fb_text(fb, xL, y, "BLOCKS", 1, C_DIM);
    snprintf(val, sizeof(val), "%lld", st->blocks_found);
    fb_text(fb, xLv, y, val, 1, st->blocks_found ? C_OK : C_TEXT);
    if (st->blocks_found) {
        fb_text(fb, xR, y, "LAST", 1, C_DIM);
        fmt_age(st->last_block ? now - (time_t)st->last_block : -1L, age, sizeof(age));
        fb_text(fb, xRv, y, age, 1, C_TEXT);
    }
    y += 14;

    fb_text(fb, xL, y, "TEMP",  1, C_DIM);
    if (st->temp_c >= -50 && st->temp_c <= 150) {  /* sane DS18B20 range */
        snprintf(val, sizeof(val), "%ldC", st->temp_c);
        fb_text(fb, xLv, y, val, 1, st->temp_c >= 65 ? C_WARN : C_TEXT);
    } else {
        fb_text(fb, xLv, y, "--", 1, C_DIM);
    }
    fb_text(fb, xR, y, "FAN", 1, C_DIM);
    if (st->fan_rpm >= 0)
        snprintf(val, sizeof(val), "%ld%% %ld", st->fan_duty_pct, st->fan_rpm);
    else
        snprintf(val, sizeof(val), "%ld%%", st->fan_duty_pct);
    fb_text(fb, xRv, y, val, 1, st->fan_duty_pct > 0 ? C_OK : C_DIM);
    y += 14;

    /* Pool share acceptance rate */
    long long total = st->shares_accepted + st->shares_rejected;
    if (total > 0) {
        int pct = (int)(st->shares_accepted * 100LL / total);
        fb_text(fb, xL, y, "ACC/REJ", 1, C_DIM);
        snprintf(val, sizeof(val), "%lld/%lld  %d%%",
                 st->shares_accepted, st->shares_rejected, pct);
        fb_text(fb, xLv, y, val, 1,
                pct >= 90 ? C_OK : pct >= 70 ? C_WARN : C_BAD);
        y += 14;
    }
    /* I/O backend (UIO interrupt-driven vs /dev/mem polling) */
    if (st->backend[0]) {
        fb_text(fb, xL, y, "BACKEND", 1, C_DIM);
        fb_text(fb, xLv, y, st->backend, 1,
                strcmp(st->backend, "uio") == 0 ? C_OK : C_TEXT);
    }
}

/* ---- Screen-settings page: hit rects returned to main loop ---- */
typedef struct {
    rect_t timeout_dec, timeout_inc;
    rect_t level_dec,   level_inc;
} settings_rects_t;

/* ---- Action sheet (MENU): one modal list of system actions, opened from the
   consistent MENU button on every info screen so actions + settings + WiFi live
   in one predictable place rather than scattered/duplicated across screens. ---- */
enum { AS_GLANCE, AS_DETAIL, AS_SETUP, AS_WIFI, AS_RESTART, AS_REBOOT, AS_CANCEL, AS_N };
static rect_t action_rect(const fb_t *fb, int i)
{
    int w = 220, h = 26, gap = 3;
    int total = AS_N * h + (AS_N - 1) * gap;
    rect_t r = { (fb->w - w) / 2, (fb->h - total) / 2 + i * (h + gap), w, h };
    return r;
}
static void draw_action_sheet(fb_t *fb)
{
    static const char *lbl[AS_N] = { "GLANCE", "DETAIL", "SETUP", "WIFI SETUP",
                                     "RESTART", "REBOOT", "CANCEL" };
    /* modal panel behind the list */
    rect_t top = action_rect(fb, 0), bot = action_rect(fb, AS_N - 1);
    int pad = 12;
    fb_rect(fb, top.x - pad, top.y - pad, top.w + 2 * pad,
            (bot.y + bot.h - top.y) + 2 * pad, C_ACCENT);
    fb_rect(fb, top.x - pad + 1, top.y - pad + 1, top.w + 2 * pad - 2,
            (bot.y + bot.h - top.y) + 2 * pad - 2, C_BG);
    for (int i = 0; i < AS_N; i++) {
        rect_t r = action_rect(fb, i);
        uint16_t border = (i == AS_REBOOT) ? C_BAD : (i == AS_CANCEL) ? C_PANEL : C_ACCENT;
        uint16_t tc     = (i == AS_REBOOT) ? C_BAD : (i == AS_CANCEL) ? C_TEXT  : C_ACCENT;
        fb_rect(fb, r.x, r.y, r.w, r.h, border);
        fb_rect(fb, r.x + 1, r.y + 1, r.w - 2, r.h - 2, C_PANEL);
        fb_text(fb, r.x + (r.w - fb_text_w(1, lbl[i])) / 2, r.y + 10, lbl[i], 1, tc);
    }
}

static settings_rects_t draw_settings(fb_t *fb, int dim_timeout, int dim_level)
{
    bg_blit(fb);
    settings_rects_t r;
    char buf[32];
    int cw = fb->w;

    int y = 10;
    const char *title = "SETUP";
    fb_text(fb, (cw - fb_text_w(1, title)) / 2, y, title, 1, C_ACCENT);
    y += 22;

    /* DIM TIMEOUT row */
    fb_text(fb, 8, y, "DIM TIMEOUT", 1, C_DIM);
    y += 16;
    snprintf(buf, sizeof(buf), dim_timeout == 0 ? "NEVER" : "%ds", dim_timeout);
    r.timeout_dec = (rect_t){ 8,       y, 36, 26 };
    r.timeout_inc = (rect_t){ cw - 44, y, 36, 26 };
    fb_rect(fb, r.timeout_dec.x, r.timeout_dec.y, r.timeout_dec.w, r.timeout_dec.h, C_ACCENT);
    fb_text(fb, r.timeout_dec.x + (36 - fb_text_w(1, "-")) / 2, y + 8, "-", 1, C_BG);
    fb_text(fb, (cw - fb_text_w(1, buf)) / 2, y + 8, buf, 1, C_TEXT);
    fb_rect(fb, r.timeout_inc.x, r.timeout_inc.y, r.timeout_inc.w, r.timeout_inc.h, C_ACCENT);
    fb_text(fb, r.timeout_inc.x + (36 - fb_text_w(1, "+")) / 2, y + 8, "+", 1, C_BG);
    y += 38;

    /* DIM LEVEL row */
    fb_text(fb, 8, y, "DIM LEVEL", 1, C_DIM);
    y += 16;
    snprintf(buf, sizeof(buf), dim_level == 0 ? "BLANK" : "%d%%", dim_level);
    r.level_dec = (rect_t){ 8,       y, 36, 26 };
    r.level_inc = (rect_t){ cw - 44, y, 36, 26 };
    fb_rect(fb, r.level_dec.x, r.level_dec.y, r.level_dec.w, r.level_dec.h, C_ACCENT);
    fb_text(fb, r.level_dec.x + (36 - fb_text_w(1, "-")) / 2, y + 8, "-", 1, C_BG);
    fb_text(fb, (cw - fb_text_w(1, buf)) / 2, y + 8, buf, 1, C_TEXT);
    fb_rect(fb, r.level_inc.x, r.level_inc.y, r.level_inc.w, r.level_inc.h, C_ACCENT);
    fb_text(fb, r.level_inc.x + (36 - fb_text_w(1, "+")) / 2, y + 8, "+", 1, C_BG);
    y += 36;

    const char *hint = dim_level == 0
        ? "0=blank off  1-100=dim to %" : "1-100=dim to % brightness";
    fb_text(fb, 8, y, hint, 1, C_DIM);

    return r;
}

/* Full-screen celebratory takeover when a NEW block is found, replacing the
 * normal dashboard until the user taps to dismiss (see block_ack_* and the
 * main loop). A real find is rare and worth a hard-to-miss screen, not a
 * small status-line entry that could be missed scrolling past. */
static rect_t block_found_dismiss_rect(const fb_t *fb)
{
    rect_t r = { 6, fb->h - 42, fb->w - 12, 34 };
    return r;
}

static void draw_block_found(fb_t *fb, const status_t *st, time_t now)
{
    fb_rect(fb, 0, 0, fb->w, fb->h, C_BG);
    fb_rect(fb, 0, 0, fb->w, 4, C_ACCENT);
    fb_logo(fb, fb->w / 2 - 16, 20, 2);
    const char *title = "BLOCK FOUND!";
    fb_text(fb, (fb->w - fb_text_w(2, title)) / 2, 64, title, 2, C_ACCENT);

    char line[64];
    snprintf(line, sizeof(line), "blocks found: %lld", st->blocks_found);
    fb_text(fb, (fb->w - fb_text_w(1, line)) / 2, 104, line, 1, C_TEXT);

    char age[24], aline[64];
    fmt_age(st->last_block ? now - (time_t)st->last_block : -1L, age, sizeof(age));
    snprintf(aline, sizeof(aline), "%s", age);
    fb_text(fb, (fb->w - fb_text_w(1, aline)) / 2, 122, aline, 1, C_DIM);

    rect_t r = block_found_dismiss_rect(fb);
    fb_rect(fb, r.x, r.y, r.w, r.h, C_ACCENT);
    fb_rect(fb, r.x + 1, r.y + 1, r.w - 2, r.h - 2, C_BG);
    const char *d = "TAP TO CLEAR";
    fb_text(fb, r.x + (r.w - fb_text_w(1, d)) / 2, r.y + 11, d, 1, C_ACCENT);
}

/* Blocks until the user taps the dismiss button (or g_stop fires). Boards
 * with no touch hardware can't clear it manually, so just hold it on screen
 * briefly rather than locking the dashboard out forever. */
static void run_block_banner(fb_t *fb, touch_t *tp, int have_touch,
                              const status_t *st, time_t now)
{
    draw_block_found(fb, st, now);
    if (!have_touch) {
        struct timespec ts = { 5, 0 };
        nanosleep(&ts, NULL);
        return;
    }
    rect_t r = block_found_dismiss_rect(fb);
    while (!g_stop) {
        int sx, sy;
        if (touch_poll(tp, fb, &sx, &sy) && hit(&r, sx, sy))
            return;
        struct timespec ts = { 0, 100 * 1000000L };
        nanosleep(&ts, NULL);
    }
}

/* Centered splash: shield logo + ODO MINER + a status/loading message. */
static void draw_splash(fb_t *fb, const char *msg)
{
    fb_rect(fb, 0, 0, fb->w, fb->h, C_BG);
    fb_logo(fb, fb->w / 2 - 16, fb->h / 2 - 52, 2);            /* 32x32 */
    const char *title = "ODO MINER";
    fb_text(fb, (fb->w - fb_text_w(2, title)) / 2, fb->h / 2 - 12, title, 2, C_TEXT);
    fb_text(fb, (fb->w - fb_text_w(1, msg)) / 2, fb->h / 2 + 16, msg, 1, C_ACCENT);
}

int main(int argc, char **argv)
{
    /* Splash mode: `odo-ui splash "message"` paints a centered splash and
     * exits — used by the init scripts to show boot progress on the TFT. */
    if (argc >= 2 && strcmp(argv[1], "splash") == 0) {
        fb_t sfb;
        if (fb_open(&sfb) != 0) return 1;
        draw_splash(&sfb, argc >= 3 ? argv[2] : "Loading...");
        struct timespec ts = { 0, 300 * 1000000L };  /* let fbtft push it out */
        nanosleep(&ts, NULL);
        return 0;
    }

    const char *status_path = argc > 1 ? argv[1] : "/run/odod/status.json";

    signal(SIGINT, on_sig);
    signal(SIGTERM, on_sig);

    fb_t fb;
    if (fb_open(&fb) != 0)
        return 1;
    fb_init_fonts();
    bg_load(&fb);

    touch_t tp;
    int have_touch = touch_open(&tp) == 0;
    if (!have_touch)
        fprintf(stderr, "odo-ui: no ADS7846 touch device found; display-only mode\n");

    /* button row — wide left (DETAILS / ← BACK), two narrow (WIFI/RESTART, MENU/REBOOT) */
    rect_t btn_left  = { 6,   fb.h - 42, 148, 34 };  /* confirm-dialog layout */
    rect_t btn_mid   = { 160, fb.h - 42,  74, 34 };
    rect_t btn_right = { 240, fb.h - 42,  74, 34 };
    rect_t menu_btn  = { fb.w - 62, fb.h - 42, 56, 34 };  /* compact hamburger, bottom-right */

    /* WiFi setup keyboard layout */
    kbkey_t keys[64];
    int nk = kb_build(keys, fb.w);
    /* initial load: no WiFi configured yet -> open the setup screen */
    if (have_touch && access(WPA_CONF, F_OK) != 0)
        run_wifi_setup(&fb, &tp, keys, nk, have_touch);

    load_ui_conf();

    int confirm = 0;            /* 0 none, 1 confirm-restart, 2 confirm-reboot */
    int menu_open = 0;          /* action sheet (MENU) visible */
    int rebooting = 0;
    time_t confirm_at = 0;
    int ui_screen = 0;          /* 0 = glance, 1 = detail, 2 = screen settings */
    long long block_ack = -1;   /* -1 = not yet seeded from the first status read */

    /* Screen-settings hit rects (the +/- controls edit g_dim_* live and auto-save) */
    settings_rects_t set_rects;
    memset(&set_rects, 0, sizeof(set_rects));

    /* Reload screen config from disk periodically (web UI may have changed it) */
    int conf_reload_tick = 0;

    g_last_activity = time(NULL);

    while (!g_stop) {
        time_t now = time(NULL);

        /* Reload screen config every ~20 iterations (~2s) so web UI changes
         * take effect without restarting odo-ui. Skip while in settings page
         * (user may be mid-edit). */
        if (ui_screen != 2 && ++conf_reload_tick >= 20) {
            conf_reload_tick = 0;
            load_ui_conf();
        }

        if (rebooting) {
            draw_splash(&fb, "Rebooting...");
            struct timespec ts = { 0, 400 * 1000000L };
            nanosleep(&ts, NULL);
            continue;
        }

        /* Auto-dim: blank/dim panel after g_dim_timeout seconds (0 = never) */
        if (!g_blanked && g_dim_timeout > 0 && now - g_last_activity > g_dim_timeout) {
            if (g_dim_level == 0)
                fb_set_blank(1);
            else
                fb_apply_dim(&fb, g_dim_level);
            g_blanked = 1;
        }
        if (g_blanked) {
            struct timespec ts = { 0, 200 * 1000000L };
            nanosleep(&ts, NULL);
            if (have_touch) {
                int sx, sy;
                if (touch_poll(&tp, &fb, &sx, &sy)) {
                    if (g_dim_level == 0) fb_set_blank(0);
                    g_blanked = 0;
                    g_last_activity = now;
                    /* discard this tap — it was a wake touch */
                }
            }
            continue;
        }

        status_t st;
        memset(&st, 0, sizeof(st));
        status_read(status_path, &st);

        if (block_ack < 0)
            block_ack = block_ack_load(st.blocks_found);
        if (st.blocks_found > block_ack) {
            run_block_banner(&fb, &tp, have_touch, &st, now);
            block_ack = st.blocks_found;
            block_ack_save(block_ack);
            continue;
        }

        char wssid[40]; int wdbm = 0;
        wifi_status(wssid, sizeof wssid, &wdbm);

        /* ---- draw active screen ---- */
        if (ui_screen == 0)
            draw_glance(&fb, &st, now, wssid, wdbm);
        else if (ui_screen == 1)
            draw_detail(&fb, &st, now, wssid, wdbm);
        else
            set_rects = draw_settings(&fb, g_dim_timeout, g_dim_level);

        /* ---- buttons ---- */
        if (confirm && now - confirm_at > 6)
            confirm = 0;
        if (menu_open && now - confirm_at > 10)
            menu_open = 0;

        if (confirm > 0) {
            /* Confirm dialog (restart or reboot): spans left+mid, cancel right. */
            int cw2 = btn_mid.x + btn_mid.w - btn_left.x;
            fb_rect(&fb, btn_left.x, btn_left.y, cw2, btn_left.h, C_BAD);
            fb_text(&fb, btn_left.x + 8, btn_left.y + 11,
                    confirm == 1 ? "CONFIRM RESTART" : "CONFIRM REBOOT", 1, C_TEXT);
            fb_rect(&fb, btn_right.x, btn_right.y, btn_right.w, btn_right.h, C_ACCENT);
            fb_rect(&fb, btn_right.x+1, btn_right.y+1, btn_right.w-2, btn_right.h-2, C_PANEL);
            fb_text(&fb, btn_right.x + (btn_right.w - fb_text_w(1, "CANCEL")) / 2,
                    btn_right.y + 11, "CANCEL", 1, C_TEXT);
        } else {
            /* Single compact hamburger; everything else is in the menu, and
             * glance/detail/setup are reached by swiping (see input handler). */
            fb_rect(&fb, menu_btn.x, menu_btn.y, menu_btn.w, menu_btn.h, C_ACCENT);
            fb_rect(&fb, menu_btn.x+1, menu_btn.y+1, menu_btn.w-2, menu_btn.h-2, C_PANEL);
            {   /* hamburger icon centered in the button */
                int hx = menu_btn.x + menu_btn.w / 2 - 10;
                int hy = menu_btn.y + 10;
                for (int k = 0; k < 3; k++)
                    fb_rect(&fb, hx, hy + k * 6, 20, 3, C_ACCENT);
            }
        }

        /* Action sheet draws on top of the bar when open (but under confirm). */
        if (menu_open && confirm == 0)
            draw_action_sheet(&fb);

        /* ---- input ---- */
        for (int tick = 0; tick < 20 && !g_stop; tick++) {
            int sx, sy;
            int tapped = have_touch ? touch_poll(&tp, &fb, &sx, &sy) : 0;
            if (tapped) {
                g_last_activity = now;
                /* Horizontal swipe in the content area (above button zone) switches
                 * screens without needing the button; a tap (|dx|<40) falls through
                 * to normal button handling. */
                int dx = sx - tp.press_x;
                if (abs(dx) > 40 && confirm == 0 && !menu_open) {
                    /* swipe cycles glance/detail/settings (matches the < / > bar) */
                    if      (dx < 0) ui_screen = (ui_screen + 1) % 3;
                    else             ui_screen = (ui_screen + 2) % 3;
                    tick = 99;
                } else if (confirm > 0) {
                    /* Confirm dialog: left+mid area executes, anything else cancels */
                    rect_t cfm = { btn_left.x, btn_left.y,
                                   btn_mid.x + btn_mid.w - btn_left.x, btn_left.h };
                    if (hit(&cfm, sx, sy)) {
                        if (confirm == 1) {
                            int rc = system("/etc/init.d/S90odod restart >/dev/null 2>&1 || "
                                            "systemctl restart odod >/dev/null 2>&1");
                            (void)rc;
                        } else {
                            rebooting = 1;
                            draw_splash(&fb, "Rebooting...");
                            sync();
                            int rc = system("reboot");
                            (void)rc;
                        }
                    }
                    confirm = 0;
                } else if (menu_open) {
                    /* Action sheet taps (Restart / Reboot / WiFi / Screen / Cancel);
                     * a tap outside any item dismisses the sheet. */
                    int handled = 0;
                    for (int i = 0; i < AS_N; i++) {
                        rect_t r = action_rect(&fb, i);
                        if (!hit(&r, sx, sy)) continue;
                        handled = 1;
                        if      (i == AS_GLANCE)  { ui_screen = 0; }
                        else if (i == AS_DETAIL)  { ui_screen = 1; }
                        else if (i == AS_SETUP)   { ui_screen = 2; }
                        else if (i == AS_WIFI)    { run_wifi_setup(&fb, &tp, keys, nk, have_touch); }
                        else if (i == AS_RESTART) { confirm = 1; confirm_at = now; }
                        else if (i == AS_REBOOT)  { confirm = 2; confirm_at = now; }
                        /* AS_CANCEL: just close */
                        break;
                    }
                    (void)handled;
                    menu_open = 0;
                } else {
                    /* Just the hamburger; pages are reached by swiping. */
                    if (hit(&menu_btn, sx, sy)) {
                        menu_open = 1; confirm_at = now;
                    } else if (ui_screen == 2) {
                        /* Screen-settings +/- edit g_dim_* live and persist immediately */
                        if (hit(&set_rects.timeout_dec, sx, sy)) {
                            g_dim_timeout -= 30; if (g_dim_timeout < 0) g_dim_timeout = 0;
                            save_ui_conf();
                        } else if (hit(&set_rects.timeout_inc, sx, sy)) {
                            g_dim_timeout += 30; if (g_dim_timeout > 3600) g_dim_timeout = 3600;
                            save_ui_conf();
                        } else if (hit(&set_rects.level_dec, sx, sy)) {
                            g_dim_level -= 5; if (g_dim_level < 0) g_dim_level = 0;
                            save_ui_conf();
                        } else if (hit(&set_rects.level_inc, sx, sy)) {
                            g_dim_level += 5; if (g_dim_level > 100) g_dim_level = 100;
                            save_ui_conf();
                        }
                    }
                }
                tick = 99;
            }
            struct timespec ts = { 0, 100 * 1000000L };
            nanosleep(&ts, NULL);
        }
    }

    /* Clear the panel on exit (odo-ui catches SIGTERM on reboot/stop) so a
     * stale frame doesn't linger on the TFT. Pause briefly so fbtft's
     * deferred IO pushes the cleared frame out before the process exits. */
    if (fb.pix && fb.pix != MAP_FAILED) {
        if (rebooting) draw_splash(&fb, "Rebooting...");
        else           fb_rect(&fb, 0, 0, fb.w, fb.h, RGB565(0, 0, 0));
        struct timespec ts = { 0, 250 * 1000000L };
        nanosleep(&ts, NULL);
    }

    fb_free_fonts();
    return 0;
}
