// -----------------------------------------------------------------------------
// Hash Pipeline PLL (Cyclone V)
// - Input: 50 MHz reference clock
// - Output: 150–200 MHz hash clock
// - Output: 50 MHz sync clock (optional)
// -----------------------------------------------------------------------------
module hash_pll (
    input  wire refclk,      // 50 MHz
    input  wire rst,         // active-high reset
    output wire clk_hash,    // 150–200 MHz
    output wire clk_sync,    // 50 MHz (optional)
    output wire locked
);

    // This module is generated by Quartus IP Catalog:
    // IP Catalog → Basic Functions → Clocks → PLL
    // Settings:
    //   Input: 50 MHz
    //   Output0: 150–200 MHz (choose 6.667 ns or 5.000 ns period)
    //   Output1: 50 MHz (optional)
    //   Duty cycle: 50%
    //   Jitter optimization: ON
    //   Bandwidth: HIGH

    hash_pll_qsys pll_inst (
        .refclk   (refclk),
        .rst      (rst),
        .outclk_0 (clk_hash),
        .outclk_1 (clk_sync),
        .locked   (locked)
    );

endmodule
