#!/bin/bash
# build-fpga.sh — one-command FPGA bitstream build for odo-miner-cyclonev.
#
# Runs the full flow in the right order with the gotchas handled:
#   1. Epoch RTL gen — the pipelined core bakes the OdoCrypt epoch into its
#      LUTs, so odo_<ODOKEY>.v must be generated by odo_gen for the ODOKEY in
#      the .qsf. That file is gitignored (regenerable), so a fresh clone has to
#      generate it here before anything references it.
#   2. Known-answer testbench (Icarus, WSL) — proves the pipelined RTL finds the
#      oracle's nonce bit-exact BEFORE spending an hour in Quartus.
#   3. qsys-generate — REQUIRED after any RTL edit: Platform Designer COPIES
#      hdl/src sources into soc_system/synthesis/submodules/, so skipping
#      this step silently compiles stale RTL.
#   4. quartus_sh --flow compile — synthesis through assembler (.rbf).
#   5. Sanity checks: fitter success, S-boxes actually in block RAM, no negative
#      setup slack (fabric + 156.25 MHz miner clock).
#
# Run from Git Bash on Windows (Quartus is a Windows install); needs WSL for the
# odo_gen build and the simulation gate:
#   bash scripts/build-fpga.sh
#
# Options (environment):
#   QUARTUS_ROOT=/c/altera_lite/25.1std   Quartus installation
#   SKIP_TB=1                             skip the simulation gate (not advised)
#
# Output: hdl/quartus/output_files/odo_miner.rbf
#   -> copy to the SD card FAT partition as fpga.rbf (build-sdcard.sh does
#      this automatically when the file exists).
#
# When does the FPGA need rebuilding? When RTL/Qsys/pins change — AND on every
# OdoCrypt epoch change, because the pipelined core bakes the epoch into LUTs
# (see scripts/epoch_build_deploy.ps1 for the per-epoch build+stage path).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
QUARTUS_ROOT="${QUARTUS_ROOT:-/c/altera_lite/25.1std}"

QSYS_BIN="$QUARTUS_ROOT/quartus/sopc_builder/bin"
QUARTUS_BIN="$QUARTUS_ROOT/quartus/bin64"

GREEN='\033[0;32m'; RED='\033[0;31m'; BLUE='\033[0;34m'; YEL='\033[1;33m'; NC='\033[0m'
info() { echo -e "${BLUE}[*]${NC} $*"; }
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YEL}[!]${NC} $*"; }
die()  { echo -e "${RED}[FAIL]${NC} $*"; exit 1; }

[ -x "$QUARTUS_BIN/quartus_sh.exe" ] || die "Quartus not found at $QUARTUS_ROOT (set QUARTUS_ROOT)"

REPO_WSL=$(echo "$PROJECT_ROOT" | sed 's|^/\([a-z]\)/|/mnt/\1/|')

# Read the baked epoch + throughput straight from the .qsf (the single source
# of truth for the deployed config).
QSF="$PROJECT_ROOT/hdl/quartus/odo_miner.qsf"
ODOKEY=$(grep 'VERILOG_MACRO.*ODOKEY=' "$QSF" | sed 's/.*ODOKEY=\([0-9]*\).*/\1/')
THROUGHPUT=$(grep 'VERILOG_MACRO.*THROUGHPUT=' "$QSF" | sed 's/.*THROUGHPUT=\([0-9]*\).*/\1/')
[ -n "$ODOKEY" ] && [ -n "$THROUGHPUT" ] || die "could not read ODOKEY/THROUGHPUT from $QSF"
EPOCH_RTL="$PROJECT_ROOT/hdl/src/pipelined/odo_${ODOKEY}.v"

# ----------------------------------------------------------------------------
# Step 1: generate the per-epoch RTL (baked into the pipelined core's LUTs)
# ----------------------------------------------------------------------------
# odo_<ODOKEY>.v is gitignored (regenerable), so a fresh clone won't have it.
# Generate it from odo_gen for the .qsf's ODOKEY/THROUGHPUT if missing or if the
# localparam THROUGHPUT doesn't match the .qsf (a mismatch -> wrong hash -> 0
# shares). odo_gen is a Linux C++ tool, so build+run it in WSL like the TB step.
if [ -f "$EPOCH_RTL" ] && grep -q "localparam THROUGHPUT = ${THROUGHPUT};" "$EPOCH_RTL"; then
    ok "Step 1: epoch RTL present (odo_${ODOKEY}.v, THROUGHPUT=${THROUGHPUT})"
elif command -v wsl.exe > /dev/null 2>&1; then
    info "Step 1: generating epoch RTL odo_${ODOKEY}.v (T=${THROUGHPUT}) via odo_gen..."
    wsl.exe -e bash -lc "cd '$REPO_WSL/third_party/odo-miner/src/verilog' && make odo_gen >/dev/null && ./odo_gen ${ODOKEY} ${THROUGHPUT} odo_ > '$REPO_WSL/hdl/src/pipelined/odo_${ODOKEY}.v'" \
        || die "odo_gen failed to build (check third_party/odo-miner/src/verilog/ is present and WSL has g++)"
    grep -q "localparam THROUGHPUT = ${THROUGHPUT};" "$EPOCH_RTL" \
        || die "generated $EPOCH_RTL has the wrong THROUGHPUT — odo_gen may have failed silently"
    ok "Generated odo_${ODOKEY}.v"
else
    die "epoch RTL odo_${ODOKEY}.v missing and WSL unavailable to generate it (run odo_gen ${ODOKEY} ${THROUGHPUT} odo_ > hdl/src/pipelined/odo_${ODOKEY}.v)"
fi

# ----------------------------------------------------------------------------
# Step 2: simulation gate (pipelined core)
# ----------------------------------------------------------------------------
if [ "${SKIP_TB:-0}" = "1" ]; then
    warn "Step 2: SKIPPING the known-answer testbench (SKIP_TB=1)"
elif command -v wsl.exe > /dev/null 2>&1; then
    info "Step 2: Known-answer testbench (pipelined core, Icarus in WSL)..."
    TB_DIR_WSL="$REPO_WSL/hdl/tb"
    if wsl.exe -e bash -lc "cd '$TB_DIR_WSL' && ./run_tb_pipe.sh" 2>&1 | grep -q "PIPE TB: PASS"; then
        ok "Pipelined RTL finds the oracle nonce bit-exact"
    else
        die "Testbench failed — fix the RTL before synthesizing (or SKIP_TB=1 to override)"
    fi
    if wsl.exe -e bash -lc "cd '$TB_DIR_WSL' && ./run_tb_fifo.sh" 2>&1 | grep -q "FIFO TB: PASS"; then
        ok "Found-handoff async FIFO: burst/overflow/in-order/irq-level OK"
    else
        die "FIFO testbench failed — fix the wrapper FIFO before synthesizing"
    fi
else
    warn "Step 2: WSL not available — skipping the simulation gate"
fi

# ----------------------------------------------------------------------------
# Step 3: regenerate the Platform Designer system (copies RTL into submodules)
# ----------------------------------------------------------------------------
info "Step 3: qsys-generate (refreshes the RTL copies the compile actually uses)..."
cd "$PROJECT_ROOT/hdl/qsys"
PATH="$QSYS_BIN:$PATH" qsys-generate soc_system.qsys --synthesis=VERILOG \
    --output-directory=soc_system --search-path="$(pwd),\$" > /tmp/qsys-gen.log 2>&1 \
    || die "qsys-generate failed (see /tmp/qsys-gen.log)"
# Read the active fileset straight from pipelined_miner_hw.tcl rather than a
# hardcoded list -- odo_0 is `pipelined_miner_top`, not the legacy single/dual
# -core `odocrypt_top`/`odocrypt_core` FSM design, and the epoch RTL file
# (odo_<seed>.v) changes per autocompile, so a fixed list goes stale.
while read -r relpath; do
    f="$(basename "$relpath")"
    src_md5=$(md5sum "$relpath" 2>/dev/null | cut -d' ' -f1)
    gen_md5=$(md5sum "soc_system/synthesis/submodules/$f" 2>/dev/null | cut -d' ' -f1)
    [ -n "$src_md5" ] && [ "$src_md5" = "$gen_md5" ] || die "stale submodule copy: $f (qsys did not refresh it)"
done < <(grep -oP 'add_fileset_file\s+\S+\s+VERILOG\s+PATH\s+\K\S+' pipelined_miner_hw.tcl)
ok "Platform Designer system generated; submodule copies verified current"

# ----------------------------------------------------------------------------
# Step 4: full Quartus compile (30-60 min)
# ----------------------------------------------------------------------------
info "Step 4: Quartus full compile (synthesis -> fitter -> timing -> .rbf)..."
cd "$PROJECT_ROOT/hdl/quartus"
"$QUARTUS_BIN/quartus_sh.exe" --flow compile odo_miner > /tmp/quartus-flow.log 2>&1 \
    || die "Quartus flow failed (see /tmp/quartus-flow.log and output_files/*.rpt)"

# ----------------------------------------------------------------------------
# Step 5: sanity checks
# ----------------------------------------------------------------------------
info "Step 5: Checking results..."
grep -q "Fitter Status : Successful" output_files/odo_miner.fit.summary \
    || die "Fitter failed — see output_files/odo_miner.fit.rpt"

ram_blocks=$(grep -oE "Total RAM Blocks : [0-9]+" output_files/odo_miner.fit.summary | grep -oE "[0-9]+$" || echo 0)
[ "$ram_blocks" -ge 60 ] \
    || die "Only $ram_blocks RAM blocks used (expected >=60) — S-box BRAM inference regressed; see docs/TODO.md fit history"

# No negative slack on ANY clock (fabric ~55 MHz + the 156.25 MHz miner clock).
# The summary lists each clock's slack; a leading '-' on any is a violation.
if grep -qE "Slack[[:space:]]*:[[:space:]]*-" output_files/odo_miner.sta.summary; then
    die "Timing FAILED (negative slack on some clock) — see output_files/odo_miner.sta.rpt"
fi

alm=$(grep -oE "Logic utilization \(in ALMs\) : [0-9,]+ / [0-9,]+" output_files/odo_miner.fit.summary || true)
ok "Fit successful ($alm; $ram_blocks RAM blocks; timing met)"
ok "Bitstream: hdl/quartus/output_files/odo_miner.rbf"
echo
echo "Next: copy to the SD card boot partition as fpga.rbf"
echo "  (scripts/build-sdcard.sh picks it up automatically)"
