#!/usr/bin/env python3
"""Extract the full FPGA ball-function map + connector nets from the board PDF
and emit a categorized markdown reference.

Usage: python3 scripts/extract_schematic.py [pdf] > docs/SCHEMATIC_FPGA_PINOUT.md
"""
import sys, re
import pypdf

PDF = sys.argv[1] if len(sys.argv) > 1 else \
    "docs/QMTECH_Cyclone_V_SoC_KFB_Dual_SDRAM_Schematic_20240607_V01.pdf"

# Plausible Cyclone V U484 ball rows (no I, O, Q). Used to drop text-extraction
# artifacts where a net-name fragment merged with the next token's ball.
ROWS = {c for c in "ABCDEFGHJKLMNPRTUVWY"} | {"AA","AB","AC","AD","AE","AF","AG","AH","AJ","AK"}
ball_at_end = re.compile(r'([A-K]?[A-Z])([0-9]{1,2})\Z')

r = pypdf.PdfReader(PDF)
pins = {}
for p in r.pages:
    for raw in (p.extract_text() or '').splitlines():
        for tok in re.split(r'\s+', raw.strip()):
            m = ball_at_end.search(tok)
            if not m:
                continue
            row, col = m.group(1), m.group(2)
            if row not in ROWS:
                continue
            func = tok[:m.start(1)]
            if not func or not ('/' in func or 'HPS_' in func):
                continue
            pins.setdefault(row + col, set()).add(func.strip('/').strip()[:72])

def cat(f):
    f = f.upper()
    if 'HPS_DDR' in f or 'HPS_RZQ' in f:                       return '1. HPS DDR3'
    if any(k in f for k in ('SDMMC','RGMII','USB0','USB1','NAND','QSPI',
                            'HPS_CLK','HPS_NRST','HPS_NPOR','HPS_POR','HPS_T',
                            'I2C','HPS_GPIO','CAN','UART','SPIM','HPS_EN')):  return '2. HPS peripherals / GPIO'
    if any(k in f for k in ('DCLK','AS_DATA','ASDO','NCSO','NCEO','MSEL',
                            'CONF_DON','NSTATUS','NCONFI','DATA','TCK','TMS','TDO')): return '3. Config / JTAG'
    if 'CLK' in f or 'FPLL' in f:                              return '4. Clocks / PLL'
    if 'IO/DIFFIO' in f or 'DIFFOUT' in f or 'RZQ' in f:        return '5. FPGA fabric I/O'
    return '6. Other'

def ballkey(b):
    m = re.match(r'([A-K]?[A-Z])([0-9]+)', b)
    return (m.group(1), int(m.group(2)))

groups = {}
for b, fs in pins.items():
    groups.setdefault(cat(' '.join(fs)), []).append((b, ' / '.join(sorted(fs))))

print("# FPGA ball inventory - auto-extracted from the board schematic\n")
print("Generated by `scripts/extract_schematic.py` from")
print("`docs/QMTECH_Cyclone_V_SoC_KFB_Dual_SDRAM_Schematic_20240607_V01.pdf`.\n")
print("> Automated PDF text extraction - a few rows may carry minor merge")
print("> artifacts. The curated/verified subset (clock, reset, config, the")
print("> pins the design actually uses) is in `docs/SCHEMATIC_PINMAP.md`; the")
print("> authoritative list of *used* pins is `hdl/quartus/odo_miner.qsf`.\n")
print("Total balls captured: **%d**\n" % len(pins))
for g in sorted(groups):
    print("## %s\n" % g)
    print("| Ball | Function (schematic) |")
    print("|------|----------------------|")
    for b, f in sorted(groups[g], key=lambda x: ballkey(x[0])):
        print("| %s | %s |" % (b, f.replace('|', '\\|')))
    print()
